### ISSUE TITLE
Crash on launch after lastest update.

### ISSUE THREAD

**Issue by KostromDan** [MehVahdJukaar/Moonlight#101]
[crash-2023-04-15_14.08.02-client.txt](https://github.com/MehVahdJukaar/Moonlight/files/11239201/crash-2023-04-15_14.08.02-client.txt)
[2023-04-15-7.log](https://github.com/MehVahdJukaar/Moonlight/files/11239203/2023-04-15-7.log)

**Comment by suerion** [comment]
try the latest update #100 was fixed with it. -> is the same module with bootstrap
