### ISSUE TITLE
[1.19.4] Bow/Crossbow animations don't play when using them

### ISSUE THREAD

**Issue by ghost** [MehVahdJukaar/Moonlight#104]
Bow and crossbow animations don't play when using them. And moonlight lib is the only mod I have installed.

**Comment by YuRaNnNzZZ** [comment]
https://github.com/MehVahdJukaar/Moonlight/blob/fcd3eee13b0375ae2d312753ab5a09dca5a26be1/common/src/main/java/net/mehvahdjukaar/moonlight/core/mixins/ItemOverridesCacheMixin.java#L31-L39

https://github.com/MehVahdJukaar/Moonlight/blob/fcd3eee13b0375ae2d312753ab5a09dca5a26be1/common/src/main/java/net/mehvahdjukaar/moonlight/core/Moonlight.java#L36

**Comment by MehVahdJukaar** [comment]
That explains it. I forgot to remove that stuff was just some test I did
