### ISSUE TITLE
Crash when booting the game. re: 1.19.4-2.4.2

### ISSUE THREAD

**Issue by JackoDEJ** [MehVahdJukaar/Moonlight#105]
[crash-2023-05-14_15.54.12-client.txt](https://github.com/MehVahdJukaar/Moonlight/files/11472371/crash-2023-05-14_15.54.12-client.txt)

I tend to use chat gpt to identify the issue and moonlight lib seems to be the culprit. 
"This error is a java.lang.NoSuchMethodError originating from the 'moonlight' mod in your Minecraft instance. This kind of error usually happens when you are calling a method that doesn't exist, which could be due to a number of reasons"

**Comment by JackoDEJ** [comment]
I had removed the Dummy Mod which is not ideal for me. The game boots up now.

**Comment by MehVahdJukaar** [comment]
I update dummy. Should work again
