### ISSUE TITLE
[1.19.2] 16th of May update broke things in an odd way

### ISSUE THREAD

**Issue by twenty41** [MehVahdJukaar/Moonlight#106]
I opened CurseForge launcher today to my normal 1.19.2 modpack (in which, thus far, I've been keeping all mods up to date) to see that I had 34 mods pending an update. Irresponsibly and stupidly, I clicked "update all," hoping all would work out fine.

My game proceeded to crash on launch, experiencing an infinite Mojang loading screen, with brief glimpses of Not Enough Crashes flashing beneath, with every single character nothing but unicode squares.

Going into each mod that I just "updated" it was revealed that CurseForge actually downdated (de-updated) all 34 affected mods to versions hovering around mid-to-late 2022, most around August to October. The modpack was only created around April 28th.
I've now reverted everything and the pack seems to be working again.

This mod was the only one to release a new version today so it leads me to believe it may somehow be the cause.

<details>
<summary>Here is a list of the affected mods, all of which were downdated:</summary>
<br>

```
Additional Additions

AttributeFix

Botany Trees

Bottle Your XP

Clear Despawn

Comforts

Convenient Name Tags

Creeper Overhaul

Easy Magic

Expert Armor

Explorer's Compass

Falling Leaves

FallingTree

Friends & Foes (but neither of it's optional tweak mods)

Galosphere

Harvest with Ease

Infinity Buttons

Lithium

More Axolotl Variants Mod

Macaw's Lights and Lamps

Mystical Oak Tree

Not Enough Animations

Nutritious Milk

Raised

Resource Pack Overrides

Sound Physics Remastered

Supplementaries Squared (but not base Supplementaries)

Transparent

UnionLib

Visuality

Zombies Villagers from Spawner

Zoomify
```
</details>

**Comment by MehVahdJukaar** [comment]
Send your latest.log

**Comment by twenty41** [comment]
I'm not sure my latest.log would be useful to you as I've reverted everything and my latest launch was successful.

Incase it somehow _is_ useful (had to use a file host as it's too big for github):
https://i.bloomworldwi.de/mf5SsE

Here is an archived log from the logs folder just after the problem began:
[2023-05-16-1.log](https://github.com/MehVahdJukaar/Moonlight/files/11492901/2023-05-16-1.log)

Here is the initial crash log:
[crash-2023-05-16_16.25.15-server.txt](https://github.com/MehVahdJukaar/Moonlight/files/11492906/crash-2023-05-16_16.25.15-server.txt)

As you can see that one mentioned Zombie Villagers From Spawner as a potential culprit, after reverting that one, it gave me this crash log:
[crash-2023-05-16_16.32.09-server.txt](https://github.com/MehVahdJukaar/Moonlight/files/11492908/crash-2023-05-16_16.32.09-server.txt)

(the fact that Moonlight was updated today is what really causes my suspicion but this is probably a more relevant crash log than the above)

**Comment by MehVahdJukaar** [comment]
Issue is you are using an outdated version of mystical tree which had a bug loading configs. Today's update just changed one line in some non essential code fixing a visual bug so can't be related. In fact I don't know how it wasn't crashing before. Only explanation could be that cueseforge launcher bug that makes you "update" to older versions

**Comment by MehVahdJukaar** [comment]
Also that log you sent first is obnoxiously huge. It crashes my text editor lol. That mod there that's logging that stuff is definitely slowing your game down from all that logging each render tick

**Comment by twenty41** [comment]
Seems to be Distant Horizons LOD buffering that's taking up most of the log, yeah? Either way I have no performance complaints so whatever I guess.

I've been using the latest version of Mystical Oak Tree though so I'm not sure what you mean. The logs may show otherwise because it was one of the affected downgraded mods.

In any case, sorry to bother if it's unrelated to Moonlight

**Comment by MehVahdJukaar** [comment]
Well if you do have the latest version of mystical oak tree you need to send me the crash log that happens with that one

**Comment by brisingraerowing** [comment]
This isn't Supplementaries' fault. The CF launcher / API had a serious bug that caused it to get the wrong file for the latest version. It seems to have been mostly fixed now.
