### ISSUE TITLE
[1.19.4] Crash on boot with the most recent update.

### ISSUE THREAD

**Issue by Overkill77** [MehVahdJukaar/Moonlight#107]
After going thru my modpack, the mod of which causes this crash is ["Youve goat to be kidding me"](https://www.curseforge.com/minecraft/mc-mods/goated/files?gameVersionTypeId=4) in tandom with moonlightlib
Note: They do not crash separately, only when together of course. 

### Crash log:
[crash-2023-05-18_16.24.25-client.txt](https://github.com/MehVahdJukaar/Moonlight/files/11509132/crash-2023-05-18_16.24.25-client.txt)

Thank you for all the work you put in, and have a wonderful day!

**Comment by MehVahdJukaar** [comment]
fixed!
