### ISSUE TITLE
Crash upon switching resourcepacks

### ISSUE THREAD

**Issue by Na7uralone1** [MehVahdJukaar/Moonlight#109]
I'm not exactly sure why this happens, but anytime I change what resource pack I'm using it completely crashes the game. It says it's a soft fluid issue. Here's the crash report:

[crash-2023-06-15_17.03.03-client.txt](https://github.com/MehVahdJukaar/Moonlight/files/11763656/crash-2023-06-15_17.03.03-client.txt)

**Comment by Xelbayria** [comment]
is the issue resolved with the latest version?

**Comment by Xelbayria** [comment]
since there is no reply, i'll close this now.
