### ISSUE TITLE
`java.lang.NoSuchMethodError` for `net.mehvahdjukaar.moonlight.api.client.model.BakedQuadBuilder.create()`

### ISSUE THREAD

**Issue by GlynLeine** [MehVahdJukaar/Moonlight#116]
Crash upon rendering certain block models from other mods:
`net.mehvahdjukaar.hauntedharvest.client.CarvedPumpkinBakedModel.createPixelQuad(CarvedPumpkinBakedModel.java:143)`
crash log: [crash-2023-07-11_17.35.24-client.txt](https://github.com/MehVahdJukaar/Moonlight/files/12016483/crash-2023-07-11_17.35.24-client.txt)

**Comment by drakray** [comment]
Got the same thing with MC 1.20.1, Forge 47.1.21
https://pastebin.com/dgZJtSFx
Different modpack, same Haunted Harvest (3.1.9)

**Comment by Xelbayria** [comment]
is the issue resolved with the latest version?

**Comment by drakray** [comment]
I would think so, I use NeoForge 47.1.79, Moonlight 2.8.50 and Haunted Harvest 3.1.10 and didn't crash, so 😅

**Comment by Xelbayria** [comment]
👍 Alright, if the same issue comes back, then you can re-open this issue with the **Moonlight** version and **Haunted Harvest** version. 
Have fun playing!
