### ISSUE TITLE
Moonlight Changelog for latest version

### ISSUE THREAD

**Issue by Gamemassa** [MehVahdJukaar/Moonlight#117]
Hi, I noticed that the changelog for the latest version of Moonlight (2.6.1 Forge and Fabric) just says "Fixe an Issue", and I guess I was just curious what that issue actually was, and/or if there's a more detailed changelog here in GitHub I can look at instead.

**Comment by MehVahdJukaar** [comment]
I think it was a crash with another one of my mods since I changed some internal stuff

**Comment by Gamemassa** [comment]
Oh, gotcha. Yeah, ever since the whole scare a few months ago with those handful of mods on Modrinth/Curseforge that had infected updates, I've been a lot more cautious when I don't see a changelog. (Granted none of the mods with infected updates were in mine or my friends' modpacks even before they were infected, so I never even went to their pages let alone downloaded any of them, but I'm still a cautious person).

**Comment by MehVahdJukaar** [comment]
If I were a hacker uploading a changelog to make it look authentic I would write it way longer than that one. Could scan the mod class names and be creative with it too

**Comment by Gamemassa** [comment]
Good point, but the article from back then warning about the infected updates said they had no changelogs (I think). But more importantly, you probably wouldn't have responded to a post in your GitHub either.
