### ISSUE TITLE
Missing Required Datapacks

### ISSUE THREAD

**Issue by Lars-ellery02** [MehVahdJukaar/Moonlight#118]
Hello,

I have installed Moonlight on my pc for a server but when I connect to the server it tells me:

Missing required datapack registries: moonlight:map_markers, moonlight:soft_fluids

I can’t find any solutions online. Please help

**Comment by MehVahdJukaar** [comment]
That can only ever happen if the mod is either not installed on server or some other weird mod is nuking hard the datapack registries. Velocity was known for this bug but they fixed. Are you on forge? If so it's not my issue as datwpack registries are natively supported by forge api

**Comment by Lars-ellery02** [comment]
> That can only ever happen if the mod is either not installed on server or some other weird mod is nuking hard the datapack registries. Velocity was known for this bug but they fixed. Are you on forge? If so it's not my issue as datwpack registries are natively supported by forge api

Yeah I’m on forge. I’ll try reinstalling on the client and serve and see if that works. The two fixes I’ve seen is people just reinstalling it

**Comment by Xelbayria** [comment]
Is the issue resolved?

**Comment by Xelbayria** [comment]
since there is no reply, i'll close this.
