### ISSUE TITLE
Exit Code: -1

### ISSUE THREAD

**Issue by SmellyBozoAce** [MehVahdJukaar/Moonlight#119]
Crashes before Minecraft even opens and says "The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'moonlight'!"

**Comment by SmellyBozoAce** [comment]
The version is Fabric 1.20.1

**Comment by MehVahdJukaar** [comment]
I need latest.log. exit code 1 doesn't mean anything

**Comment by MehVahdJukaar** [comment]
But it's likely outdated mods

**Comment by SmellyBozoAce** [comment]
It was the mod better lilypads
