### ISSUE TITLE
Moonlight librarry (moonlight) has failed to load correctly

### ISSUE THREAD

**Issue by Fiolettovy** [MehVahdJukaar/Moonlight#120]
Hi, today I updated my modpack and since ive done it this error message keep showing up.
Already tried to reinstal several times but nothing as changed this message is still showing.
If anyone can help i'll take it !

**Comment by jouki** [comment]
Attaching the crash log from crash while loading the game
[crash-2023-07-18_01.03.05-fml.txt](https://github.com/MehVahdJukaar/Moonlight/files/12074339/crash-2023-07-18_01.03.05-fml.txt)
![image](https://github.com/MehVahdJukaar/Moonlight/assets/1493141/15e525fc-8e9d-41da-9d77-03600fce9466)

**Comment by Fiolettovy** [comment]
This is exactly this one

**Comment by nevercamearound** [comment]
same it works when I go back a version

**Comment by MehVahdJukaar** [comment]
You need new forge

**Comment by Fiolettovy** [comment]
So, here is the crash log https://pastebin.com/ehKSiTtT

**Comment by MehVahdJukaar** [comment]
As I've said, you need new forge

**Comment by Fiolettovy** [comment]
Im with curseforge so technically its already the newer version

**Comment by MehVahdJukaar** [comment]
It is not. Curseforge has nothing to do with it. Latest version is 47.1.28. you got 47.1.0

**Comment by Fiolettovy** [comment]
Okay ill try then

**Comment by Fiolettovy** [comment]
It worked ! Thx for the help and sorry for the disturbance

**Comment by jouki** [comment]
> It is not. Curseforge has nothing to do with it. Latest version is 47.1.28. you got 47.1.0

Thank you for clarifying, if it would be possible to mention it in the changelog so it can be found this new requirement :)
Cheers
