### ISSUE TITLE
[1.20.1][Better Jukebox] Dedicated server crash - showing up in stacktrace

### ISSUE THREAD

**Issue by ProsperCraft** [MehVahdJukaar/Moonlight#122]
Sorry, I couldn't find the Better jukebox issue tracker.

Better Jukebox is showing up in this stacktrace, so I was hoping you and the other mod author could take a peek at it.

https://github.com/MC-U-Team/Overworld-Mirror/issues/59

**Comment by MehVahdJukaar** [comment]
Mod doesn't currently work on servers. It's written on mod page
