### ISSUE TITLE
Incompatibily with Better Lily Pads

### ISSUE THREAD

**Issue by DEAFG0AT** [MehVahdJukaar/Moonlight#124]
Here is my crash report:
[crash-2023-07-28_21.15.33-server.txt](https://github.com/MehVahdJukaar/Moonlight/files/12206266/crash-2023-07-28_21.15.33-server.txt)

**Comment by Xelbayria** [comment]
have you tried the latest version to check if the issue still persists?

**Comment by Xelbayria** [comment]
You need to make sure that both Client and Server are using the same version for every mods you install on both. 

Since there are no reply, I'll close this now.
