### ISSUE TITLE
unknown or not serialised registry when joining fabric 1.19.2 server

### ISSUE THREAD

**Issue by duskydoesstuff** [MehVahdJukaar/Moonlight#135]
someone is trying to join my Fabric 1.19.2 server and this is happening. other people can play on the server.
crash image: (cant access log) https://media.discordapp.net/attachments/1137506900188082310/1146849216069636136/image.png?width=780&height=439

**Comment by MehVahdJukaar** [comment]
that can only ever happen if client/server dont have the mod or even worse are a vanilla one

**Comment by duskydoesstuff** [comment]
Sorry i solved the issue, turned out he did not install fabric API because it was missing from the files i sent him/didnt transfer for some reason
