### ISSUE TITLE
Crashes with 2.8.18 and 2.8.19

### ISSUE THREAD

**Issue by terzag** [MehVahdJukaar/Moonlight#143]
Hello,
After updating to 2.8.18, the game crashes silently on startup. I have this in the log: https://pastebin.com/kHGtTDwu
With 2.8.19, it's a bit different as I get a Java window for the crash: https://pastebin.com/iM2Cnzep

I know this is a bit of a mess with a lot of mods but I also have a crash on a minimal profile with only Fabric API, Moonlight (2.8.19) and Storage Labels: https://pastebin.com/CNZuFcCi
2.8.18 works with that profile, though.

Reverting to 2.8.17 works with both profiles.

**Comment by GabbyDG2805** [comment]
I have the same problem

**Comment by ChromaPIE** [comment]
exactly the same problem

**Comment by ChromaPIE** [comment]
same problem. temp workaround (or maybe the problem is just this simple) is deleting the `"SelfCustomItemRendererProvider",` line in `moonlight.mixins.json`. im on my main menu now.

**Comment by Poopooracoocoo** [comment]
Fixed in 2.8.20 thanks to https://github.com/MehVahdJukaar/Moonlight/commit/20cfaafb678fb017da291e8b86e770ae6b4df54e
