### ISSUE TITLE
Client side crashes on moonlight-1.20-2.7.2-forge

### ISSUE THREAD

**Issue by j0dles** [MehVahdJukaar/Moonlight#144]
A member of my server keeps crashing when placing flowerpots and using ropes (supplementaries mod). Other members are fine so assuming it's client side.
They get the message "The game crashed whilst unexpected error
Error: java.lang.NullPointerException: Registry Object not present: moonlight:placeable_item" 

New to mods so unsure how to advise them.

Thanks.

**Comment by MehVahdJukaar** [comment]
Use latest version

**Comment by Xelbayria** [comment]
has the latest version fixed the issue?

**Comment by Xelbayria** [comment]
Since there is no reply, I assume the latest version has resolved the issue.
