### ISSUE TITLE
2.8.22 causing crash on minecraft 1.20.1 Quilt

### ISSUE THREAD

**Issue by NolanHewitt** [MehVahdJukaar/Moonlight#145]
Crashes on startup, 2.8.21 works without issue.

[crash-2023-09-15_21.34.21.7926-quilt_loader.txt](https://github.com/MehVahdJukaar/Moonlight/files/12639709/crash-2023-09-15_21.34.21.7926-quilt_loader.txt)

**Comment by DanMeadWasTaken** [comment]
same here, https://mclo.gs/Q2d7RuN

**Comment by BugmanBugman** [comment]
Happening on forge

**Comment by torialityy** [comment]
Happening on Fabric

**Comment by Wionsito** [comment]
Same

**Comment by Xelbayria** [comment]
is the issue resolved?

**Comment by Xelbayria** [comment]
Since there are no replying, I'll close this because a similar issue related to this have been closed, too
