### ISSUE TITLE
Loot table related crash after I opened a sunken ship chest

### ISSUE THREAD

**Issue by ImpulsiveLass** [MehVahdJukaar/Moonlight#147]
Forge 47.1.3
moonlight-1.20-2.8.23-forge
I cannot open the world without immediately crashing unless I remove moonlight

[moonlight crash.txt](https://github.com/MehVahdJukaar/Moonlight/files/12642164/moonlight.crash.txt)

**Comment by Mitchell5200** [comment]
Adding onto this, seems to be a buried treasure map that's causing the crash, and yes removing moonlight and supplementaries fixes it
https://mclo.gs/660qkgt 

*Edit, using moonlight 2.8.21 fixes this*

**Comment by Mitchell5200** [comment]
Fixed by moonlight 2.8.24, for me anyway

**Comment by ImpulsiveLass** [comment]
Can confirm the crash was patched in 2.8.24, closing issue.
