### ISSUE TITLE
1.20.1 crash on opening buried treasure

### ISSUE THREAD

**Issue by ImpulsiveLass** [MehVahdJukaar/Moonlight#148]
forge 47.1.3
moonlight-1.20-2.8.24

[buried treasure crash.txt](https://github.com/MehVahdJukaar/Moonlight/files/12643203/buried.treasure.crash.txt)

**Comment by MehVahdJukaar** [comment]
Does it happen with latest version?

**Comment by ImpulsiveLass** [comment]
I did not get the crash again but I was unable to replicate the crash in either the new version or the 2.8.24 version when I tested a few minutes ago

**Comment by Xelbayria** [comment]
@ImpulsiveLad 
is the issue resolved?

**Comment by ImpulsiveLass** [comment]
Hasn’t crashed since
