### ISSUE TITLE
Moonlight crash with Twilight Forest Magic Map recently on 1.20.1 and can't load world

### ISSUE THREAD

**Issue by Lerrycapetime** [MehVahdJukaar/Moonlight#152]
Not sure if this is Twilight Forest, Xaero's or something else but whenever I grab the magic map and put it in my inventory hotbar whether if it's in a chest or creative mode, it'll instantly crash the game with the log below.

Version 1.20.1-forge-47.1.46
moonlight-1.20-2.8.33-forge

[crash-2023-09-28_21.35.04-server.txt](https://github.com/MehVahdJukaar/Moonlight/files/12756127/crash-2023-09-28_21.35.04-server.txt)

**Comment by Xelbayria** [comment]
Can you also attach `latest.log` here, too. We can find out what's going on.

**Comment by MehVahdJukaar** [comment]
this was resolved
