### ISSUE TITLE
1.20.2 port

### ISSUE THREAD

**Issue by gohkenytp** [MehVahdJukaar/Moonlight#153]
I hate to do this, but would you kindly port all your mods to Minecraft Forge 1.20.2? Thank you!

**Comment by MehVahdJukaar** [comment]
My dude neoforge isn t even out

**Comment by gohkenytp** [comment]
Well the original forge for Minecraft 1.20.2 is actually out.

**Comment by MehVahdJukaar** [comment]
and nobody will use it

**Comment by gohkenytp** [comment]
Well almost everyone (bagu_chan updates his mods to that version)

**Comment by MehVahdJukaar** [comment]
That's literally just one . All forge community will move to neoforge. I'm already developing for it and I believe the hard split might occur in 1.21 not this update like I thought or hoped. Regardless no talk about this will be had before neoforge releases. And btw I'm spending much time in this stuff, way more than even the most avid modded player, I know the in and outs of the game code and im well connected in the community so I'm well aware of when an update is out meaning I don't need reminders as soon as it comes out. If a mod hasn't been updatedthat means it's being worked on or is waiting to be worked on as my time is not unlimited
