### ISSUE TITLE
[quilt 1.20.1] 2.8.42 causing game to crash with other mods

### ISSUE THREAD

**Issue by glittermutt** [MehVahdJukaar/Moonlight#154]
crash report attached. it seems completely random, you can turn on a mod and itll work, then turn it off and turn it on back again and it suddenly will start crashing
[crash-2023-10-02_14.46.12-client.txt](https://github.com/MehVahdJukaar/Moonlight/files/12781604/crash-2023-10-02_14.46.12-client.txt)

**Comment by MehVahdJukaar** [comment]
I need latest.lof

**Comment by Xelbayria** [comment]
Please attach the `latest.log` here, so we can find out what's going on.
