### ISSUE TITLE
Problems with Moonlight every time Supplimentaries and Moonlight is updated.

### ISSUE THREAD

**Issue by SirTwsted** [MehVahdJukaar/Moonlight#156]
I just updated Supplementaries and Moonlight together as they both at the same time have updates (as usual).
Ok with that said, 
The problem is that every time Supplementaries and moonlight is updated,  the game complains that
there is a problem. The latest update is the following.

Moonlight-1.20-2.8.44-forge.jar
supplementaries-1.20-2.6.9.jar

But the game complains that a version of moonlight is missing.  Even though there is no such version released.

![Screenshot_114](https://github.com/MehVahdJukaar/Moonlight/assets/15247713/21580304-df7e-42d1-b1c5-df4485a34533)

Even though there is no such version released as shown here in the following.

![Screenshot_116](https://github.com/MehVahdJukaar/Moonlight/assets/15247713/56d4d7a8-b69e-4c94-87a8-867fc17d740d)

THEN when I try to go backwards back the to the version I previously had installed,  so I can continue to play the game.
This is what I get in return.

![Screenshot_115](https://github.com/MehVahdJukaar/Moonlight/assets/15247713/065dc4bc-cf86-452c-b3d0-9863d238861b)

So now I can't even play the game anymore,  because its now broken both ways.  Upgrading and falling back to previous version,

🤷‍♀️

**Comment by CsillaAria** [comment]
I am having the same issue. This happened to me with citadel a few days ago.

**Comment by S0apyy** [comment]
same issue when trying to update my modpack. supplementaries decides to update to a library mod version thats not even released yet

**Comment by MehVahdJukaar** [comment]
Sometimes curseforge takes time to approve files
