### ISSUE TITLE
Java runtime error caused by Moonlight prevents the game from loading 

### ISSUE THREAD

**Issue by Axolotlus275** [MehVahdJukaar/Moonlight#157]
The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'moonlight'!

I'm running moonlight for supplementaries and Spelunkery on fabric version 0.11.2 for 1.20.1 

[crash-2023-10-08_09.48.12-client.txt](https://github.com/MehVahdJukaar/Moonlight/files/12840231/crash-2023-10-08_09.48.12-client.txt)
[modslist.txt](https://github.com/MehVahdJukaar/Moonlight/files/12840238/modslist.txt)

**Comment by MehVahdJukaar** [comment]
I only see an issue from geode plus. Nothing related to this

**Comment by Axolotlus275** [comment]
oh ok thanks
