### ISSUE TITLE
1.20.1 Neoforge crashes when opening map

### ISSUE THREAD

**Issue by MeiyuanaQ** [MehVahdJukaar/Moonlight#159]
Neoforge 1.20.1 47.1.56  and above
OptiFine_1.20.1_HD_U_I6_pre6
[错误报告-2023-10-10_12.23.13.zip](https://github.com/MehVahdJukaar/Moonlight/files/12852747/-2023-10-10_12.23.13.zip)

**Comment by MeiyuanaQ** [comment]
If there is a map in the inventory, it will crash.

**Comment by MehVahdJukaar** [comment]
try without optifine

**Comment by Ll66dar** [comment]
> try without optifine

Then indicate what is not compatible with optifine.

**Comment by MehVahdJukaar** [comment]
Why would I? Optifine is literally incompatible with forge in 1.19 and has been known to cause countless issues to mods thought the years due to the way it's coded, vet different from a normal forge mod. No reason anybody should ever use optifine with mods

**Comment by Xelbayria** [comment]
That's not all, I heard that Optifine become a closed-source. There are better mods that can do the same thing as Optifine. 

are you able to find out what caused the crash?
