### ISSUE TITLE
Dont know what's causing this. mod conflict?

### ISSUE THREAD

**Issue by FuturisticDruid** [MehVahdJukaar/Moonlight#160]
Don't know where I should be posting an issue at but this happened after adding Moonlight and Supplementaries to my server

the 2nd skin layer is not showing up for anyone
![image](https://github.com/MehVahdJukaar/Moonlight/assets/128937884/688d2311-1bcd-4962-8cae-2c1d8d21448a)

villagers are shown as unemployed villagers even though they have jobs
![image](https://github.com/MehVahdJukaar/Moonlight/assets/128937884/a50344f4-629d-4181-a7f1-6d032e29d08a)

and mob attack animations are bugged (skeleton shooting bow at me but not aiming at me)
![image](https://github.com/MehVahdJukaar/Moonlight/assets/128937884/7becfae5-dcbb-4b64-be16-a9822ce39ecb)

here is mod list
[Modlist.txt](https://github.com/MehVahdJukaar/Moonlight/files/12888114/Modlist.txt)

also baby animals are not shown as babies
![image](https://github.com/MehVahdJukaar/Moonlight/assets/128937884/88e0a1f7-6810-4939-9811-fb8f4cdee239)

**Comment by FuturisticDruid** [comment]
weird thing is that none of this happens in singleplayer world

**Comment by FuturisticDruid** [comment]
oh should mention that I am on 1.20.1

**Comment by MehVahdJukaar** [comment]
i cant replicate this. try with just moonlight and not supplementaries

**Comment by Xelbayria** [comment]
no reply, will be closing this
