### ISSUE TITLE
Incompatibility with TwilightForests Magic Map 1.20.1

### ISSUE THREAD

**Issue by litjohn50** [MehVahdJukaar/Moonlight#161]
Issue: When opening a magic map from Twilight Forest it disconnects me with the screenshot below.
 There is no way to rejoin the world without removing editing player data. Other friends also get the same error.

![image](https://github.com/MehVahdJukaar/Moonlight/assets/28884916/b452e6e4-8850-454b-b59a-5ce1566dbcb1)

![image](https://github.com/MehVahdJukaar/Moonlight/assets/28884916/8e74dabe-29c8-45e9-a762-da97b474ffa4)

It doesn't seem to be recreateable with only twilight forest and Moonlight installed (maybe because Moonlight is just a library)
But it is repeatable when other models that use moonlight are installed.

https://github.com/TeamTwilight/twilightforest/issues/1890

Forge- 47.1.3
moonlight-1.20-2.8.49-forge
twilightforest-1.20.1-4.3.1850-universal
labels-1.20-1.16.jar
supplementaries-1.20-2.6.12.jar
dummmmmmy-1.20-1.8.3.jar
suppsquared-1.20-1.1.10.jar <- idk why I included this one in the profile but its there so I mentioned it

logs: https://gist.github.com/litjohn50/7a5fcfe7f61ba86618bf52a1c1aee6af

debug log: https://gist.github.com/litjohn50/efae910eddec1c368b71af3b8f1c4327

**Comment by muon-rw** [comment]
Update moonlight lib to 2.8.50

**Comment by litjohn50** [comment]
its fixed thanks
