### ISSUE TITLE
1.20.1 forge [OptiFine] crashed when picked up a treasure map or using normal map

### ISSUE THREAD

**Issue by Primia** [MehVahdJukaar/Moonlight#162]
Moonlight Lib forge_1.20-2.8.50

**Comment by Primia** [comment]
https://mclo.gs/AdIg52W

**Comment by Silveere** [comment]
I am also experiencing this issue. It seems like might be related to #147. The only difference is that my partner and I are playing on a server and the bugged map would cause a disconnect, and then I had to manually edit the NBT data to remove the bugged item so he could reconnect. The server log doesn't show any error, it seems to be a client side issue.

https://mclo.gs/fzfSwub#L12758

**Comment by Serrobii** [comment]
Same thing is happening with v2.8.47. Been playing on a server with some friends, and my game started crashing after picking up a treasure map in a sunken ship, and the crashing still persists long after the map was removed. I cannot join the world with both OptiFine and this mod enabled at the same time.

[crash log](https://mclo.gs/zD1uhwh)

**Comment by TierraVulture** [comment]
I had this happen to me too

**Comment by Xelbayria** [comment]
update to Moonlight v2.8.51, that's the latest version and check if the issue still persists. 

Please fill out the following info if you have a similar issue: 
- **Loader:** Forge or Fabric????

**Comment by TierraVulture** [comment]
> update to Moonlight v2.8.51, that's the latest version and check if the issue still persists. 
> 
> 
> 
> Please fill out the following info if you have a similar issue: 
> 
> - **Loader:** Forge or Fabric????
> 
> 

I was using 2.8.51 on forge when the bug happened

**Comment by forgotmypancakes** [comment]
> > update to Moonlight v2.8.51, that's the latest version and check if the issue still persists.
> > Please fill out the following info if you have a similar issue:
> > 
> > * **Loader:** Forge or Fabric????
> 
> I was using 2.8.51 on forge when the bug happened

Happens on 2.8.56 on Fabric as well... I opened another issue. Hopefully it gets fixed soon, it makes treasure hunting really annoying

**Comment by Xelbayria** [comment]
There are better alternative mods to replace Optifine. You may or may not know this detail: 
Optifine is closed-source. This move makes it difficult for devs to make their mods more compatible with Optifine. The Optifine is most likely to prevent the other mods from properly working or breaking the other mods. 

Using Optifine in vanilla Minecraft is fine.

**Comment by MehVahdJukaar** [comment]
This issue is due to optifine. If fabric has some issues then it's not the same one. Il close as issue template specifically says not to use optifine
