### ISSUE TITLE
Moonlight keeps crashing Minecraft. The last working version of Moonlight is 2.8.47 and i play minecraft 1.20.1 with forge 47.1.43. Ans if i reach the main menu of minecraft there comes a notice which says "ressources could be loaded"

### ISSUE THREAD

**Issue by jensjcs** [MehVahdJukaar/Moonlight#166]
### BEFORE CONTINUING:

- [X] Always check you are using the latest version of this mods and it's dependencies

### Version-Loader

1.20.1-forge

### Moonlight Lib Version

moonlight 2.8.54

### Issue Detail

The last working version of moonlight for me is 2.8.47. All later versions don't work and give me a notice in the main menu, that reloading of the ressources failed. And if the forge loader switches from window to full screen i get also an "error during mod loading".

### Log Attachment

[launcher_log.txt](https://github.com/MehVahdJukaar/Moonlight/files/13216998/launcher_log.txt)

### OPTIONAL: Which mods are affected?

the last version of supplementaries which i could use is 2.6.11. Later versions don't work.

**Comment by MehVahdJukaar** [comment]
Does it work without optifine?

**Comment by jensjcs** [comment]
Moonlight 2.8.54 and without optifine there i get the same notice in the loading screen and in the main menu.

**Comment by MehVahdJukaar** [comment]
send the new log you get without otifine. Also be sure all mods are updated. Also try removing some mods and see if it still happens

**Comment by Ledom-Software** [comment]
I encounter the same problem up to the latest version - Moonlight silently fails and when I join a server in creative I get no inventory tabs and the errors only show up on phisical-client-side logs

**Comment by MehVahdJukaar** [comment]
what do you mean no inventory tabs? also send a log

**Comment by Ledom-Software** [comment]
Updating to the latest version AND deleting all config files solved the issue for me
