### ISSUE TITLE
[🐞]: Filling a map causes the game to crash

### ISSUE THREAD

**Issue by forgotmypancakes** [MehVahdJukaar/Moonlight#169]
### BEFORE CONTINUING:

- [X] Always check you are using the latest version of these mods and its dependencies
- [X] Remove known problematic rendering mods such as Optifine, Sodium and others

### Version-Loader

1.20.1-fabric

### Moonlight Lib Version

moonlight-1.20-2.8.59-fabric

### Issue Detail

Filling any empty map (treasure map is what caused it for me), causes the game to freeze completely before crashing in single player and hard crash to desktop on my modded server with the same version. 

### Log Attachment

[latest.log](https://github.com/MehVahdJukaar/Moonlight/files/13316152/latest.log)
[crash-2023-11-02_01.20.22-client.txt](https://github.com/MehVahdJukaar/Moonlight/files/13316160/crash-2023-11-02_01.20.22-client.txt)
crash report is from the last time it happened on the server.

### OPTIONAL: To Produce

Find shipwreck
Find Buried Treasure map in shipwreck
Right click to fill the map
crash

### OPTIONAL: Which mods are affected?

The whole game.

**Comment by MehVahdJukaar** [comment]
You are not using latest supplementaries

**Comment by forgotmypancakes** [comment]
at the time of the server crash, both mods were up to date

**Comment by MehVahdJukaar** [comment]
False. Log says otherwise

**Comment by Xelbayria** [comment]
@forgotmypancakes 
you should go into your folder and make sure all of the mods are updated and no older versions remain.

**Comment by ehx-v1** [comment]
Note for everyone: If a "mixin failed" happens in the latest release (unlike here as it seems, but possible nonetheless), most of the time either the mod loader itself or (in the case of Fabric like here) Fabric API is either outdated or has a recent breaking change.
