### ISSUE TITLE
[🐞]: Crash on startup

### ISSUE THREAD

**Issue by ChromaPIE** [MehVahdJukaar/Moonlight#171]
### BEFORE CONTINUING:

- [X] Always check you are using the latest version of these mods and its dependencies
- [ ] Remove known problematic rendering mods such as Optifine, Sodium and others

### Version-Loader

1.20.1-fabric

### Moonlight Lib Version

moonlight-1.20-2.8.60-fabric

### Issue Detail

Title.

### Log Attachment

https://pastebin.com/h6SVJxec

### OPTIONAL: Which mods are affected?

In the report the mod name "noxesium" can be seen often, but it's already there 2 months ago, been through hundreds of successful bootups

**Comment by MehVahdJukaar** [comment]
the only thing that moonlight has to do here is be unfortunate enough as to be the first mod to load tat class where that mixin is. The rest i see on the log is indeed a failed mixin from that noxesium mod

**Comment by ChromaPIE** [comment]
ok imma report it to their side then. thanks for the fast support!

**Comment by MehVahdJukaar** [comment]
btw i checked and that mod is definitely at fault. They should either seti overwrite.conformVisibility to truein mixin config or better yet not use overwrite inthe first place as its terrible practice and there are no instances where it should be used

**Comment by ChromaPIE** [comment]
yea but they just wont fix their mod for 1.20.1. already deleted that mod.
