### ISSUE TITLE
[🐞]: New update causes mixin crash on launch

### ISSUE THREAD

**Issue by ffuentesm** [MehVahdJukaar/Moonlight#172]
### BEFORE CONTINUING:

- [X] Always check you are using the latest version of these mods and its dependencies
- [X] Remove known problematic rendering mods such as Optifine, Sodium and others

### Version-Loader

1.20.1-forge

### Moonlight Lib Version

moonlight-1.20-2.8.62-forge

### Issue Detail

After the new update, minecraft is not launching with moonlight installed. 
I tried to launch it without moonlight and it works.

### Log Attachment

https://mclo.gs/CaUuuKs

### OPTIONAL: Which mods are affected?

Supplementaries

**Comment by MehVahdJukaar** [comment]
New update includes newest mixing extras version. Some mod you have uses the older version and that mod might have had a breaking change recently so they need to update too

**Comment by ffuentesm** [comment]
Well, I solved that by just dropping mixinextras-forge-0.3.1.jar jar from here into the mods folder
https://repo1.maven.org/maven2/io/github/llamalad7/mixinextras-forge/0.3.1
