### ISSUE TITLE
[🐞]:  A warning appears when it already appears directly in the world

### ISSUE THREAD

**Issue by KaxelDreamhack123** [MehVahdJukaar/Moonlight#180]
### BEFORE CONTINUING:

- [X] Always check you are using the latest version of these mods and its dependencies
- [ ] Remove known problematic rendering mods such as Optifine, Sodium and others

### Version-Loader

1.20.1-forge

### Moonlight Lib Version

1.20-2.8.67

### Issue Detail

The following kind of warning appears: [20:41:32] [Chunk Render Task Executor #4/WARN]: Class net.mehvahdjukaar.moonlight.api.client.model.forge.BakedQuadBuilderImpl does not support optimized vertex writing code paths, which may cause reduced rendering performance

I understand the fact that I have optimizing mods like Embeddium, Radium, Starlight, Fix gpu Memory leak, Smooth Chunk and others, it just doesn't make much sense to play good modpacks without these mods. I also decided to check if the problem is related to Smooth Chunk and no, it is not related, because after removing this mod, the problem persisted. I am not sure that this warning will remind you of itself during the passage of the game, in the sense that performance will decrease, but optimization is extremely important to me, perhaps you are familiar with this problem and I would be very glad to hear your opinion on this matter. 

It's funny that after the recent update of the Supplementaries, the OpenGL 1802 error clogging the log (I don't remember exactly) disappeared when I was playing with the Excalibur resource pack

### Log Attachment

[latest.log](https://github.com/MehVahdJukaar/Moonlight/files/13688288/latest.log)

### OPTIONAL: To Produce

Install all the mods listed below, launch the world and check the log.

### OPTIONAL: Which mods are affected?

<details>
<summary>List of Mods</summary>

- accelerateddecay 3.0.1+mc1.20.1
- adaptive_performance_tweaks_core 10.2.0
- adaptive_performance_tweaks_items 10.0.0
- advancementplaques 1.4.10
- aiimprovements 0.5.2
- alexscaves 1.0.9
- alexsmobs 1.22.6
- alternate_current 1.7.0
- ambientsounds 5.3.5
- apotheosis 7.1.0
- appleskin 2.5.1+mc1.20.1
- architectury 9.1.12
- armorcurve 3.0
- ars_nouveau 4.8.1
- artifacts 9.2.0
- asynclocator 1.3.0
- atlaslib 1.1.10b
- attributefix 21.0.4
- attributeslib 1.2.1
- bagus_lib 1.20.1-4.2.1
- balm 7.2.1
- beautify 2.0.2
- betterarcheology 1.1.0
- betterdeserttemples 1.20-Forge-3.0.3
- betterdungeons 1.20-Forge-4.0.3
- betterf3 7.0.2
- betterfortresses 1.20-Forge-2.0.5
- betterfpsdist 1.20.1-4.1
- betterjungletemples 1.20-Forge-2.0.4
- bettermineshafts 1.20-Forge-4.0.4
- betteroceanmonuments 1.20-Forge-3.0.4
- betterstrongholds 1.20-Forge-4.0.3
- bookshelf 20.1.6
- bosses_of_mass_destruction 1.0.6
- bwncr 3.17.0
- bygonenether 1.3.2
- caelus 3.1.0+1.20
- cataclysm 1.0
- catalogue 1.8.0
- citadel 2.4.9
- cloth_config 12.0.109
- clumps 12.0.0.3
- collective 7.16
- colorfulhearts 4.0.4
- comforts 6.3.4+1.20.1
- conjurer_illager 1.1.6
- connectivity 1.20.1-4.8
- controlling 12.0.2
- corundumguardian 2.1.1
- create 0.5.1.f
- creativecore 2.11.14
- creeperoverhaul 3.0.1
- cristellib 1.1.5
- ctov 3.3.6
- cucumber 7.0.6
- cullleaves 3.2.0
- cupboard 1.20.1-2.1
- curios 5.4.5+1.20.1
- darkpaintings 17.0.4
- defaultoptions 18.0.1
- deuf 1.20.1-1.3
- dummmmmmy 1.20-1.8.13
- dungeons_arise 2.1.57-1.20.1
- easy_npc 3.5.0
- eidolon 1.20.1-0.3.7.5
- elevatorid 1.20.1-lex-1.9
- embeddium 0.2.13+mc1.20.1
- enchantwithmob 1.20.1-11.4.1
- enchdesc 17.0.9
- endermanoverhaul 1.0.3
- endrem 5.2.3-R-1.20.1
- ends_delight 1.0.1
- enhancedai 2.0.5
- enhancedvisuals 1.6.9
- entityculling 1.6.2
- epicfight 20.6.3
- expandability 9.0.0
- expanded_ecosphere 3.2.3
- extremesoundmuffler 3.41-forge-1.20
- fallingleaves 2.1.0
- farlanders 1.4.1
- farmersdelight 1.20.1-1.2.3
- fastbench 8.0.2
- fastfurnace 8.0.1
- fastload 3.4.0
- fastpaintings 1.20-1.2.3
- fastsuite 5.0.1
- ferritecore 6.0.1
- flywheel 0.6.10-7
- forge 47.2.17
- forgeconfigscreens 8.0.2
- fpsreducer 1.20-2.5
- ftbessentials 2001.2.2
- ftblibrary 2001.1.4
- ftbquests 2001.3.0
- ftbteams 2001.1.4
- ftbultimine 2001.1.2
- fullstackwatchdog 1.0.1+1.19.2-forge
- functionalstorage 1.20.1-1.2.6
- gateways 4.2.2
- geckolib 4.3.1
- goety 2.5.4.0
- gpumemleakfix 1.20.1-1.8
- guardvillagers 1.20.1-1.6.3
- handcrafted 3.0.5
- highlighter 1.1.8
- hunters_return 1.20.1-11.2.0
- iceberg 1.1.18
- illagerinvasion 8.0.3
- immediatelyfast 1.2.8+1.20.4
- improvedmobs 1.20.1-1.11.6
- incendium 5.3.4
- incontrol 1.20-9.1.3
- infernalmobs 1.20.1.1
- insanelib 1.12.1
- inventoryessentials 8.2.1
- inventorysorter 23.0.1
- itemfilters 2001.1.0-build.59
- jearchaeology 1.20.1-1.0.3
- jei 15.9999
- justenoughprofessions 3.0.1
- krypton 0.2.3
- kubejs 2001.6.4-build.114
- legendary_monsters 1.20.1
- legendarytooltips 1.4.5
- libertyvillagers 2.0.0+forge+1.20.1
- logbegone 1.0.8
- lootr 0.7.29.68
- magistuarmory 8.2
- majruszlibrary 7.0.2
- majruszsdifficulty 1.9.3
- maxhealthfix 12.0.2
- medievalmusic 1.20.1-2.1
- midnightlib 1.4.1
- minecraft 1.20.1
- mixinextras 0.3.0
- mixinsquared 0.1.1
- modernfix 5.10.1+mc1.20.1
- monsterplus 1.0
- moonlight 1.20-2.8.67
- mousetweaks 2.25
- mr_mine_treasure 1.3.2
- mr_upgraded_mobs 1.3.1
- mutantmonsters 8.0.6
- naturescompass 1.20.1-1.11.2-forge
- nerb 0.3
- neruina 1.3.0
- netherportalfix 13.0.1
- nochatreports 1.20.1-v2.2.2
- notenoughanimations 1.6.4
- oculus 1.6.13
- orcz 0.82
- out_of_sight 1.20.1-1.0.3
- patchouli 1.20.1-83-FORGE
- placebo 8.6.0
- ponderjs 1.3.0
- prism 1.0.5
- puzzlesaccessapi 8.0.7
- puzzleslib 8.1.11
- radium 0.12.2+git.5f80f74
- reeses_sodium_options 1.0.4
- regions_unexplored 0.5.3
- rei_plugin_compatibilities 12.0.93
- resourcefulconfig 2.1.0
- resourcefullib 2.1.19
- rhino 2001.2.2-build.18
- roughlyenoughitems 12.0.684
- rubidium 0.7.1
- rubidium_extra 0.5.3.1+mc1.20.1-build.110
- sapience 1.20.1-1.0.0
- saturn 0.1.0
- sculk_expansion_mr 1.3.0
- searchables 1.0.2
- sereneseasons 9.0.0.46
- shouldersurfing 1.20.1-2.8.1
- smoothboot 0.0.3
- sophisticatedbackpacks 3.19.4.978
- sophisticatedcore 0.5.111.517
- sound_physics_remastered 1.20.1-1.3.0
- spark 1.10.53
- spectrelib 0.13.14+1.20.1
- stackablepotions 1.0.0
- starlight 1.1.2+forge.1cda73c
- structure_gel 2.15.1
- supplementaries 1.20-2.7.8
- t_and_t 0.0NONE
- tenshilib 1.20.1-1.7.2
- terrablender 3.0.0.169
- terralith 2.4.11
- textrues_embeddium_options 0.1.3+mc1.20.1
- theoneprobe 1.20.1-10.0.0
- titanium 3.8.24
- tlc 1.0.2
- toastcontrol 8.0.3
- travelerstitles 1.20-Forge-4.0.1
- treechop 0.18.3
- tumbleweed 0.5.5
- villagernames 7.1
- waystones 14.1.1
- weaponmaster 3.0.6
- wstweaks 9.0.1
- xaerominimap 23.9.3
- yeetusexperimentus 2.3.0-build.4+mc1.20.1
- ysns 1.0.2
- yungsapi 1.20-Forge-4.0.2
- yungsbridges 1.20-Forge-4.0.3
- yungsextras 1.20-Forge-4.0.3

</details>

**Comment by MehVahdJukaar** [comment]
That is unrelated to your issue. Its a WARN after all and a harmless one. your error comes from sound physics

**Comment by KaxelDreamhack123** [comment]
> That is unrelated to your issue. Its a WARN after all and a harmless one. your error comes from sound physics

Do you mean the OpenGL error? To be more precise, this is OpenGL 1282. I tried to remove Sound Physics from mods and the error still remained, but as soon as I remove the Excalibur resource pack, the error clogging my log disappeared. I think that describing this problem here would be inappropriate, so I'll try to fix it myself.

**Comment by KaxelDreamhack123** [comment]
> > That is unrelated to your issue. Its a WARN after all and a harmless one. your error comes from sound physics
> 
> Do you mean the OpenGL error? To be more precise, this is OpenGL 1282. I tried to remove Sound Physics from mods and the error still remained, but as soon as I remove the Excalibur resource pack, the error clogging my log disappeared. I think that describing this problem here would be inappropriate, so I'll try to fix it myself.

**Comment by MehVahdJukaar** [comment]
so is this solved? the log you sent doesnt even have the GL 1802  error you are talking about

**Comment by KaxelDreamhack123** [comment]
> s

Oh, forgive my inattention. I have sent you different latest.log files. The OpenGL error is 1282, not 1802, I just forgot its name. Now this error haunts me when I have removed half of the mods responsible for adding blocks, etc. The problem really seems to be a conflict between the resource pack and one of the mods, although I have not seen this before. I tried to remove all mods, leaving only the Excalibur resource pack and there is no OpenGL error.

**Comment by KaxelDreamhack123** [comment]
> so is this solved? the log you sent doesnt even have the GL 1802 error you are talking about

Oh, forgive my inattention. I have sent you different latest.log files. The OpenGL error is 1282, not 1802, I just forgot its name. Now this error haunts me when I have removed half of the mods responsible for adding blocks, etc. The problem really seems to be a conflict between the resource pack and one of the mods, although I have not seen this before. I tried to remove all mods, leaving only the Excalibur resource pack and there is no OpenGL error.
[latest.log](https://github.com/MehVahdJukaar/Moonlight/files/13697114/latest.log)

**Comment by KaxelDreamhack123** [comment]
Yeah. The problem is with oculus.

**Comment by KaxelDreamhack123** [comment]
> Yeah. The problem is with oculus.

The most remarkable thing is that after installing the shaders (in my case, Complementary Reimagined_r5.1.1 OpenGL error 1282 disappears, it's some kind of black magic.

**Comment by KaxelDreamhack123** [comment]
I just accidentally decided to install shaders and at the same time updated the Supplementaries mod and decided to launch the world, then the error disappeared, but I did not think that the devil lies in deeper details...
