### ISSUE TITLE
1.19.2-2.3.6-forge missing on Modrinth

### ISSUE THREAD

**Issue by Nycto97** [MehVahdJukaar/Moonlight#185]
Can you please upload [moonlight-1.19.2-2.3.6-forge](https://www.curseforge.com/minecraft/mc-mods/selene/files/4983974) to the [Modrinth page](https://modrinth.com/mod/moonlight/versions?l=forge&g=1.19.2)?

**Comment by Xelbayria** [comment]
@MehVahdJukaar  Let me know if you want me to take care of it.  A friendly reminder: I don't have the access to Moonlight via Modrinth.

**Comment by Nycto97** [comment]
By the looks of it, it seems like 2.3.5 got uploaded instead of 2.3.6, according to modrinth version, changelog, filename and mods.toml.

![image](https://github.com/MehVahdJukaar/Moonlight/assets/83367226/761c02a3-57da-4821-b8e6-97bab77ae6bf)

![image](https://github.com/MehVahdJukaar/Moonlight/assets/83367226/e7854fda-6380-4b95-8030-42676aaf8e02)

![image](https://github.com/MehVahdJukaar/Moonlight/assets/83367226/3b3343fb-c9c4-4638-a2a8-f433f3c7c3a0)

**Comment by Xelbayria** [comment]
@MehVahdJukaar  ☝️ 
confirmed by checking out on modrinth.com
