### ISSUE TITLE
[🐞]: Crash on start (SpoiledZ's issue)

### ISSUE THREAD

**Issue by benio1394** [MehVahdJukaar/Moonlight#187]
### BEFORE CONTINUING:

- [X] Always check you are using the latest version of these mods and its dependencies
- [X] Remove known problematic rendering mods such as Optifine, Sodium and others

### Version-Loader

1.20.1-fabric

### Moonlight Lib Version

moonlight-1.20-2.8.84 fabric

### Issue Detail

Game is crashing on start

### Log Attachment

https://pastebin.com/CYmb8iVA

**Comment by MehVahdJukaar** [comment]
you have a mod that is adding a "spolied" blockstate to the cake _class_, not block. that is terrible for compatibility and WILL crash with modded cakes that happen to override createBlockstateDefinition. It doesnt say which mod does that tho so i cant tell

**Comment by benio1394** [comment]
Thank you, apparently it was caused by spoiledZ, sorry for problem

**Comment by MehVahdJukaar** [comment]
You might want to report to them
