### ISSUE TITLE
[🐞]: Game crashes on start

### ISSUE THREAD

**Issue by Insistar** [MehVahdJukaar/Moonlight#188]
### BEFORE CONTINUING:

- [X] Always check you are using the latest version of these mods and its dependencies
- [X] Remove known problematic rendering mods such as Optifine, Sodium and others

### Version-Loader

1.20.1-fabric

### Moonlight Lib Version

moonlight-1.20.-2.8.84-fabric

### Issue Detail

Whenever i start the game, it crashes because of friends and foes and when i delete friends and foes, it crashes because of moonlight

### Log Attachment

[crash-2024-01-19_19.05.09-client.txt](https://github.com/MehVahdJukaar/Moonlight/files/13992724/crash-2024-01-19_19.05.09-client.txt)

### OPTIONAL: Which mods are affected?

Friends and foes

**Comment by MehVahdJukaar** [comment]
Says it's an error from trinkets mod

**Comment by Insistar** [comment]
Still crashes after i deleted trinkets by saying it's an error due to friends and foes
here's the new crashlog : https://[mclo.gs/uMP9qxq](https://mclo.gs/uMP9qxq)

**Comment by MehVahdJukaar** [comment]
Still days same thing that a mixin from mod trinkets failed to apply

**Comment by Insistar** [comment]
I fixed the error, i just needed to redownload some mods and it worked

**Comment by Xelbayria** [comment]
That's good. This issue will be closed since it's not related to Moonlight Lib
