### ISSUE TITLE
Crashes on launch (1.18.2)

### ISSUE THREAD

**Issue by ProoTURK** [MehVahdJukaar/Moonlight#19]
**Latest Log:** [https://pastebin.com/sWW4LttD](https://www.curseforge.com/linkout?remoteUrl=https%253a%252f%252fpastebin.com%252fsWW4LttD)

**Crash Report**: [https://pastebin.com/tsvmtMjQ](https://www.curseforge.com/linkout?remoteUrl=https%253a%252f%252fpastebin.com%252ftsvmtMjQ)

**Comment by MehVahdJukaar** [comment]
It doesnt seem to be related to this. I see mentioned the mod net.morimori0317.gamemenumodoption.ClientConfig, however I believe it might just be a failed config file. try deleting them
