### ISSUE TITLE
[🐞]: Issue with everycomp-1.20-2.6.28

### ISSUE THREAD

**Issue by border999** [MehVahdJukaar/Moonlight#192]
### BEFORE CONTINUING:

- [X] Always check you are using the latest version of these mods and its dependencies
- [X] Remove known problematic rendering mods such as Optifine, Sodium and others

### Version-Loader

1.20.1-forge

### Moonlight Lib Version

moonlight-1.20-2.9.7-forge

### Issue Detail

Not sure if I should be directing this issue to you or to Everycomp's github. But it's here so you know.

### Log Attachment

https://gist.github.com/border999/4fe687d3e44ae2c81518b8be6aa2b548

**Comment by MehVahdJukaar** [comment]
issue with japoca firing a reload very very early before items are registered and EC config is initialized. check new version, mmight get rid of crash but idk if there will be side effects still. that practice doesnt seem that safe

**Comment by border999** [comment]
grabbed new version of EC, can't find a repeat of the above issue. Seemingly resolved for now.
