### ISSUE TITLE
[🐞]: Render thread crash on treasure maps.

### ISSUE THREAD

**Issue by NetUserGet** [MehVahdJukaar/Moonlight#199]
### BEFORE CONTINUING:

- [X] Always check you are using the latest version of these mods and its dependencies
- [X] Remove known problematic rendering mods such as Optifine, Sodium and others

### Version-Loader

1.20.1-fabric

### Moonlight Lib Version

1.20-2.10.10

### Issue Detail

So while I was adventuring I found a shipwreck and a map to Buried treasure and when I opened it, it
crashed my game. Redacted for privacy. I'm pretty sure its not anything to do with sodium or iris.

### Log Attachment

[crash-2024-03-02_16.40.54-client.txt](https://github.com/MehVahdJukaar/Moonlight/files/14470965/crash-2024-03-02_16.40.54-client.txt)

### OPTIONAL: To Produce

1) Find a shipwreck or generate one.
2) Take the map and use it.

### OPTIONAL: Which mods are affected?

Supplementaries

**Comment by MehVahdJukaar** [comment]
be sure you are on latest moonlight version

**Comment by NetUserGet** [comment]
Alright, I will update to the next newly released 1.20-2.10.11.

**Comment by Tempest-5ky** [comment]
Got a crash with a normal map on a Fabric server! https://mclo.gs/fQNuX2M
Will also update to the new version and see if that fixes it

**Comment by Tempest-5ky** [comment]
Well, i'm not crashing any more, but now loading in with the map in hand gives me this, which I can't make go away. No button presses work, including trying to quit.
![image](https://github.com/MehVahdJukaar/Moonlight/assets/99220350/19f9894f-8194-4a6e-a54d-3e8de0a135a6)

**Comment by MehVahdJukaar** [comment]
What am I even looking at?

**Comment by MehVahdJukaar** [comment]
If that's chat idk what mod is printing all that unrelated stuff but it's surely not mine nor vanilla

**Comment by Tempest-5ky** [comment]
I have absolutely no idea, but this is the latest.log which has an identical mass of text and an error with similar at the end, related to the map renderer:
https://mclo.gs/TxGTzbF
"no key enabled in MapLike" then a bunch of the crap on the game screen. Just scroll to the end of the log then go up a bit:
![image](https://github.com/MehVahdJukaar/Moonlight/assets/99220350/99912907-2f2c-41bd-985c-8dac2953071c)

**Comment by Tempest-5ky** [comment]
Alright- updating it on the serverside too seems to have fixed that particular weirdness. Thank you for the help and apologies for the trouble!

**Comment by NetUserGet** [comment]
Its fixed! (No crashes on the latest version of moonlight.)
