### ISSUE TITLE
[🐞]: Latest version detected as virus by windows defender but virus total reports as safe.

### ISSUE THREAD

**Issue by KuroNeko87** [MehVahdJukaar/Moonlight#203]
### BEFORE CONTINUING:

- [X] Always check you are using the latest version of these mods and its dependencies
- [X] Remove known problematic rendering mods such as Optifine, Sodium and others

### Version-Loader

1.20.1-forge

### Moonlight Lib Version

moonlight-1.20-2.11.1-fabric

### Issue Detail

Latest version detected as virus by windows defender but virus total reports as safe.

### Log Attachment

![image](https://github.com/MehVahdJukaar/Moonlight/assets/3025021/64ff5684-8023-4d45-a5cf-3339e985112d)

**Comment by KuroNeko87** [comment]
![image](https://github.com/MehVahdJukaar/Moonlight/assets/3025021/d121603d-9757-4f2e-8042-358d38e97989)

**Comment by MehVahdJukaar** [comment]
yeah may mods are starting to get flagged. no idea what sgoing on at microsfot

**Comment by Xelbayria** [comment]
Check if Defender is outdated. just check via Settings -> Update & Security. So far, My anti-virus doesn't detect the mod as a trojan. There is also the event (Which happened in fall of 2023) where many mods got hacked with trojan and virus codes. 

Edit: 
I see you are using the latest version of Defender, so you can discard the first sentence above. My point above is that the world of programming (Microsoft, Curseforge, and so on and on is a mess). U get the idea

**Comment by mobspawner22** [comment]
So the file is safe? False positive or not I get the itch to wipe my drives now.

**Comment by MehVahdJukaar** [comment]
yes
