### ISSUE TITLE
[🐞]: Windows Defender Claiming a Trojan is in the mod

### ISSUE THREAD

**Issue by alexweber** [MehVahdJukaar/Moonlight#206]
### BEFORE CONTINUING:

- [X] Always check you are using the latest version of these mods and its dependencies
- [X] Remove known problematic rendering mods such as Optifine, Sodium and others

### Version-Loader

1.20.1-fabric

### Moonlight Lib Version

2.11.4

### Issue Detail

False positive for `Trojan:Script/Wacatac.B!ml` apprently

### Log Attachment

no log

### OPTIONAL: To Produce

download the jar hosted on Modrinth on Windows 11

**Comment by MehVahdJukaar** [comment]
nothing i can do about it

**Comment by alexweber** [comment]
Just giving you a heads up champ.

**Comment by MehVahdJukaar** [comment]
yeah thanks, i alraedy got on the hundreds of reports. we all are getting them
