### ISSUE TITLE
[🐞]: Game freezes and crashes on log when casually rowing my boat across the sea

### ISSUE THREAD

**Issue by ChromaPIE** [MehVahdJukaar/Moonlight#207]
### BEFORE CONTINUING:

- [X] Always check you are using the latest version of these mods and its dependencies
- [X] Remove known problematic rendering mods such as Optifine, Sodium and others

### Version-Loader

1.20.1-fabric

### Moonlight Lib Version

2.11.4

### Issue Detail

Title

### Log Attachment

https://mclo.gs/0pkmxMn

**Comment by MehVahdJukaar** [comment]
its very simple. Server you are on does not have this mod

**Comment by MehVahdJukaar** [comment]
Infact pretty sure you are on a vanilla server too

**Comment by ChromaPIE** [comment]
But the fact is that I'm on Singleplayer

**Comment by MehVahdJukaar** [comment]
then theres something seriously wrong with your game.  The error complains about missing data files which however are always included with the mod itself. To replicate this consistently fill up a cauldron with honey or water and place magma block below. This crash obviously never normallyhappens so somehting else must be going on

**Comment by ChromaPIE** [comment]
idk if a full log from launching the game to the crash will be of any help but here's it https://mclo.gs/cx9yqcZ

Also, i'm guessing that it might be caused by there existing an extra ```moonlight``` folder outside of the actual ```moonlight``` folder containing all data files.

**Comment by MehVahdJukaar** [comment]
what do you mean an extra folder?

**Comment by ChromaPIE** [comment]
like in the jar the structure is data/moonlight/moonlight. you can open the jar with bandizip or stuff to give it a check

**Comment by MehVahdJukaar** [comment]
Yes but where would this be? A failed download could also have caused this. Try on a new instance

**Comment by ChromaPIE** [comment]
I just downloaded moonlight-1.20-2.11.4-fabric fresh and hot from modrinth then opened the jar. the structure is exactly ```data/moonlight/moonlight```. is the file on modrinth corrupted or?

also i've edited the jar myself, corrected it to ```data/moonlight``` and played in the world for a while. it seems to be fine.

**Comment by MehVahdJukaar** [comment]
no the jar is fine, that is how its supposed to be. i told you you can replicate this by installing either amendments and placing a water cauldron on some magma or use a supplementaries jar. if issue is gone placing bothwont crash. I have no clue what could have caused, could be a failed previous download causing some files to be missing ot not legible... somehow?

**Comment by MehVahdJukaar** [comment]
if you move that data file around you will trigger this exact error as those file it needs will be missing

**Comment by Xelbayria** [comment]
> could be a failed previous download causing some files to be missing ot not legible... somehow?

MehVahdJukaar is right. Sometimes, the internet is lost and the download could be paused and then resumed. Some of the data is lost in that process. This event is very rare.

**Comment by ChromaPIE** [comment]
this is so cursed. i totally get what you guys mean (well maybe not but please forgive my stupidity) and right now im playing with that exact same mod jar with which this problem happened, but did what i said above: peeling one layer of ```moonlight``` off, and:

<img src="https://github.com/MehVahdJukaar/Moonlight/assets/56111366/57b8cc4e-ba0d-4e65-90c5-1a87053acd63" width="480" height="270"/>

well anyway, ive been playing in the instance the whole time and now it seems to be all fine. think this issue can be closed for now.

**Comment by MehVahdJukaar** [comment]
are you sure your fabric api is updated? might be that in older version it did not allow namespaced datapack registry names

**Comment by ChromaPIE** [comment]
i check mod updates on modrinth desktop almost 10 times a day lol so yeah, using fabric api 0.92.0 and fabric loader 0.15.7 and im sure its the latest for minecraft 1.20.1

**Comment by MehVahdJukaar** [comment]
i tried using those same versions and cant replicate

**Comment by ChromaPIE** [comment]
imma just close it for now. when it happens again AND comes with some possible causes i might reopen it
