### ISSUE TITLE
[🐞]: Latest Version of Moonlight Lib causes bug with Super Better Grass

### ISSUE THREAD

**Issue by 3ncanis** [MehVahdJukaar/Moonlight#209]
### BEFORE CONTINUING:

- [X] Always check you are using the latest version of these mods and its dependencies
- [X] Remove known problematic rendering mods such as Optifine, Sodium and others

### Version-Loader

1.20.1-fabric

### Moonlight Lib Version

2.11.9

### Issue Detail

The sides of snow blocks do not connect when using Moonlight Lib and Super Better Grass until you reload your resource packs (F3 + T), on the previous version (2.11.7) this does not happen.

### Log Attachment

N/A

### OPTIONAL: To Produce

1. Install Super Better Grass
2. Install Moonlight Lib

https://github.com/MehVahdJukaar/Moonlight/assets/133993378/d0e4862c-487c-435d-bd83-3053998c54f6

**Comment by MehVahdJukaar** [comment]
i cant replicate. tried with latest version of both mods without any reloads and it worked immediately

**Comment by 3ncanis** [comment]
Sorry, I am now unable to reproduce it either without installing sodium/indium. I'll try to see what I did that caused it in that video

**Comment by ghost** [comment]
![image](https://github.com/MehVahdJukaar/Moonlight/assets/146892171/8d16da1d-5eb9-49ca-86a6-f95e2afec3aa)
Happens for me with or without sodium
![image](https://github.com/MehVahdJukaar/Moonlight/assets/146892171/b681fc17-408e-443f-a722-55b7d35c3cac)

**Comment by liangmoe** [comment]
The issue seems fixed with moonlightlib 2.11.10 and above, so update moonlightlib @3ncanis
