### ISSUE TITLE
[🐞]: Crash w/ Amendments

### ISSUE THREAD

**Issue by ereese99** [MehVahdJukaar/Moonlight#215]
### BEFORE CONTINUING:

- [X] Always check you are using the latest version of these mods and its dependencies
- [X] Remove known problematic rendering mods such as Optifine, Sodium and others

### Version-Loader

1.20.1-fabric

### Moonlight Lib Version

moonlight-1.20-2.11.12

### Issue Detail

Crash upon launch

### Log Attachment

[crash-2024-04-19_22.21.05-server.txt](https://github.com/MehVahdJukaar/Moonlight/files/15048966/crash-2024-04-19_22.21.05-server.txt)

**Comment by MehVahdJukaar** [comment]
I just see an error from this mod from that 
java.lang.IllegalStateException: Trying to access unbound value 'ResourceKey[minecraft:worldgen/structure / dungeons_arise:aviary]' from registry net.minecraft.registry.SimpleRegistry$1@6f84ef4f
