### ISSUE TITLE
[🐞]: Moonlight breaking item lighting

### ISSUE THREAD

**Issue by Snownee** [MehVahdJukaar/Moonlight#216]
### BEFORE CONTINUING:

- [X] Always check you are using the latest version of these mods and its dependencies
- [X] Remove known problematic rendering mods such as Optifine, Sodium and others

### Version-Loader

1.20.1-forge

### Moonlight Lib Version

forge_1.20-2.11.12

### Issue Detail

Moonlight makes item shadow lighter

with Moonlight only:
![1](https://github.com/MehVahdJukaar/Moonlight/assets/16059084/ebe0d267-a07d-40b1-a37e-0a6b32cbce15)
without:
![2](https://github.com/MehVahdJukaar/Moonlight/assets/16059084/93e1533c-30ff-41ff-8385-ddae48cddb30)

### Log Attachment

[latest.log](https://github.com/MehVahdJukaar/Moonlight/files/15137675/latest.log)

**Comment by MehVahdJukaar** [comment]
this is a feature. The mod slightly alters the lighting parameters such that anything rendered in world has the same exact shading as blocks baked models. This means that a block rendered with a tile rendered will have same exact shading as just a bock model. In vanilla its similar but not exact. This has the side effect to also change how item are rendered but can be changed in the config to not affect stuff in guis using old lighting there

**Comment by Snownee** [comment]
I think it should be disabled by default, or at least tell the user about this change, since it's a library mod

**Comment by MehVahdJukaar** [comment]
newer versions acutually have it affect only world stuff and not gui by default. I consider the rest a fix so thats why its here. Vanilla parameters are close but not an exact match compared to whats done here
