### ISSUE TITLE
[🐞]: incompatible with GregTech-Modern

### ISSUE THREAD

**Issue by AshdoII** [MehVahdJukaar/Moonlight#223]
### BEFORE CONTINUING:

- [X] Always check you are using the latest version of these mods and its dependencies
- [X] Remove known problematic rendering mods such as Optifine, Sodium and others

### Version-Loader

1.20.1-fabric

### Moonlight Lib Version

moonlight-1.20-2.11.33-fabric

### Issue Detail

moonlight lib start to be imcompatible with GregTech-Modern since 2.11.27. 2.11.26 works fine with it. Only seems to appear on the server side. 2.11.33 work fine in the clinet side but crashes on the server side.

### Log Attachment

[crash-2024-06-13_10.23.01-server.txt](https://github.com/user-attachments/files/15812928/crash-2024-06-13_10.23.01-server.txt)
[latest.log](https://github.com/user-attachments/files/15812932/latest.log)

### OPTIONAL: To Produce

1) install fabric server 1.20.1 0.15.11
2) install gtceu-fabric-1.20.1-1.0.20.b, fabric-api-0.92.2+1.20.1, moonlight-1.20-2.11.33
3) start server, crash.

### OPTIONAL: Which mods are affected?

gtceu-fabric-1.20.1-1.0.20.b (GregTech-Modern)

**Comment by MehVahdJukaar** [comment]
Not my issue.
They are loading client only classes in FluidVariantAttributes (for their own fluids). Too bad that
![image](https://github.com/MehVahdJukaar/Moonlight/assets/24719182/28f7d7c2-ec99-4021-a7c8-cbe28ad7c115)

**Comment by AshdoII** [comment]
I'll report to them then. Great thanks.
