### ISSUE TITLE
[🐞]: Error: java.lang.NoClassDefFoundError. Fabric 1.20.1. moonlight-1.20-2.11.37-fabric + gtceu-fabric-1.20.1-1.0.20.b.

### ISSUE THREAD

**Issue by worm-in-concrete** [MehVahdJukaar/Moonlight#224]
### BEFORE CONTINUING:

- [X] Always check you are using the latest version of these mods and its dependencies
- [X] Remove known problematic rendering mods such as Optifine, Sodium and others

### Version-Loader

1.20.1-fabric

### Moonlight Lib Version

moonlight-1.20-2.11.37-fabric

### Issue Detail

The error occurs on the hosting server. When running the client crash does not happen, but when I run these two mods (moonlight-1.20-2.11.37-fabric + gtceu-fabric-1.20.1-1.0.20.b) on the hosting server it crashes. Separately the mods work fine. I also tried to run the server with a standalone porting_lib mod.

### Log Attachment

[crash-2024-06-16_18.33.48-server.txt](https://github.com/user-attachments/files/15858929/crash-2024-06-16_18.33.48-server.txt) - https://mclo.gs/RGRrd2h
[latest.log](https://github.com/user-attachments/files/15858930/latest.log) - https://mclo.gs/0i9RowA

### OPTIONAL: Which mods are affected?

GregTechCEu Modern
https://modrinth.com/mod/gregtechceu-modern/version/mc1.20.1-1.0.20.b-fabric

**Comment by MehVahdJukaar** [comment]
bug from this mod. A part of their code which should be server safe (as dictated by fabric api docs) is not
"gregtechceu"
Unrelated to this mod

**Comment by worm-in-concrete** [comment]
Okay, thanks.
