### ISSUE TITLE
[🐞]: Crashes with Sounds mod

### ISSUE THREAD

**Issue by soyamilky101** [MehVahdJukaar/Moonlight#231]
### BEFORE CONTINUING:

- [X] Always check you are using the latest version of these mods and its dependencies
- [X] Remove known problematic rendering mods such as Optifine, Sodium and others

### Version-Loader

1.20.1-fabric

### Moonlight Lib Version

1.20-2.12.4

### Issue Detail

Hello! I'm semi-new to modding (I at least have the basics down)

This lib mod has been working fine in my personal modpack until I added the sounds mod. It crashes when I try to start up Minecraft.
https://modrinth.com/mod/sound
https://github.com/IMB11/Sounds

The log says something about moonlight lib and sounds mod. I already opened a thread for sounds mod!
I've tried it with Sodium and without, but the gist seems to be the same?
I've also tried with different builds for 1.20.1, same issue arises
If anyone could provide some insight it would be really great. Thank you so much!

### Log Attachment

[crash-2024-06-29_16.59.43-client.txt](https://github.com/user-attachments/files/16039438/crash-2024-06-29_16.59.43-client.txt)

### OPTIONAL: To Produce

Run moonlight lib and sounds mod together

### OPTIONAL: Which mods are affected?

Sounds mod

**Comment by Xelbayria** [comment]
Will be in v2.6.65

**Comment by MehVahdJukaar** [comment]
Issue does not come from this mod. The getSoundType method of that mod isnt safe to call and its their issue

**Comment by soyamilky101** [comment]
Thank you!
