### ISSUE TITLE
[🐞]: Most recent version causes crash when attempting to create a new world and an error when loading up an already existing save on Forge 1.20.1

### ISSUE THREAD

**Issue by DancingDragoness** [MehVahdJukaar/Moonlight#240]
### BEFORE CONTINUING:

- [X] Always check you are using the latest version of these mods and its dependencies
- [X] Remove known problematic rendering mods such as Optifine, Sodium and others

### Version-Loader

1.20.1-forge

### Moonlight Lib Version

moonlight forge_1.20-2.12.8

### Issue Detail

On the specified version of Moonlight Lib, when a Create New World is selected, the game crashes when the text reads Saving New World. When attempting to load a previous save, an in-game message reads "Errors in currently selected data packs prevented the mod from loading." Switching to the previous version of Moonlight Libs does not cause any crash, error message, or perceivable issue. 

This process was repeated on two different Modrinth profiles and the outcome was the same.

### Log Attachment

[crash-2024-07-17_20.43.57-client.txt](https://github.com/user-attachments/files/16276237/crash-2024-07-17_20.43.57-client.txt)
[crash-2024-07-17_19.56.54-client.txt](https://github.com/user-attachments/files/16276240/crash-2024-07-17_19.56.54-client.txt)

### OPTIONAL: To Produce

1) Lauch game after updating Moonlight Lib to forge_1.20.1-2.12.8 on a Forge 1.20.1 profile on Modrinth.
2) Either open previous save to receive same error message as described above or click Create New World and the game will crash when the text reads Saving New World.

**Comment by brisingraerowing** [comment]
[My game output](https://gist.github.com/brisingraerowing/3e133979af9699c615688e0ab959778d)

Lots of JSON errors.

ETA: Looked at one of the offending files. There's a missing `,`.

**Comment by SaltSouls** [comment]
Yup, getting the same issue.

**Comment by Xelbayria** [comment]
Someone fixed the JSON error. _brisingraerowing_ is correct about the missing comma. 

EDIT: 
I ran test on my side. there is one more JSON with the missing comma and extra bracket.

**Comment by Xelbayria** [comment]
Anyone who is familiar with "Datapack" or "JSON". please take a look at this: [mushroom_stew.json](https://github.com/MehVahdJukaar/Moonlight/blob/363edb08080a5f1bcf288e21e9f7b039f1a9daa1/common/src/main/resources/data/moonlight/moonlight/soft_fluids/mushroom_stew.json#L23)

it has 2 "food", i don't think that would work blc i had the crash on my side. 


EDIT: 

Fixed. Got some help from someone who pointed out the wrong part (need to be removed)
