### ISSUE TITLE
[🐞]:Windows defender Blocks moonlight-lib as trojan 

### ISSUE THREAD

**Issue by WalEl6512** [MehVahdJukaar/Moonlight#241]
### BEFORE CONTINUING:

- [X] Always check you are using the latest version of these mods and its dependencies
- [X] Remove known problematic rendering mods such as Optifine, Sodium and others

### Version-Loader

1.20.1-forge

### Moonlight Lib Version

moonlight-1.20-2.12.8

### Issue Detail

Windows Defender Flags moonlight-lib as Trojan.
`10:48:01.041 game [10:48:01] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 10.0.9+10.0.9+main.dcd20f30 starting: java version 21.0.3 by Eclipse Adoptium; OS Windows 11 arch amd64 version 10.0

10:48:01.480game Exception in thread "main" cpw.mods.niofs.union.UnionFileSystem$UncheckedIOException: java.nio.file.FileSystemException: D:\Minecraft on SSD\1.20.1 Heavypack\mods\moonlight-1.20-2.12.8-forge.jar: Der Vorgang konnte nicht erfolgreich abgeschlossen werden, da die Datei einen Virus oder m�glicherweise unerw�nschte Software enth�lt

10:48:01.480 game Caused by: java.nio.file.FileSystemException: D:\Minecraft on SSD\1.20.1 Heavypack\mods\moonlight-1.20-2.12.8-forge.jar: Der Vorgang konnte nicht erfolgreich abgeschlossen werden, da die Datei einen Virus oder m�glicherweise unerw�nschte Software enth�lt

10:48:01.480 game at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:92)`

Seems quiet Problematic to me.
![image](https://github.com/user-attachments/assets/eeacaca2-812f-4f06-9af7-d51492ad4d4e)

### Log Attachment

[latest.log](https://github.com/user-attachments/files/16323591/latest.log)

### OPTIONAL: Which mods are affected?

moonlight-lib

**Comment by MehVahdJukaar** [comment]
Not my issue. You should report to windows defender

**Comment by Xelbayria** [comment]
FYI, Windows Defender is developed by Microsoft. that's who you want to report. that should be a "false positive".
