### ISSUE TITLE
[🐞]: 1.21 variant crashes

### ISSUE THREAD

**Issue by 3gf8jv4dv** [MehVahdJukaar/Moonlight#242]
### BEFORE CONTINUING:

- [X] Always check you are using the latest version of these mods and its dependencies
- [X] Remove known problematic rendering mods such as Optifine, Sodium and others

### Version-Loader

1.21-Fabric&NeoForge

### Moonlight Lib Version

1.21-2.14.0

### Issue Detail

Crash when launching game

### Log Attachment

Fabric *(Deleted)*
NeoForge *(Deleted)*

**Comment by MehVahdJukaar** [comment]
fixed
