### ISSUE TITLE
[🐞]: [1.21}Moonlight latest version crashed with Charging Gadgets installed

### ISSUE THREAD

**Issue by Periam** [MehVahdJukaar/Moonlight#243]
### BEFORE CONTINUING:

- [X] Always check you are using the latest version of these mods and its dependencies
- [X] Remove known problematic rendering mods such as Optifine, Sodium and others

### Version-Loader

1.20.4-forge

### Moonlight Lib Version

moonlight-1.21-2.14.5-neoforge

### Issue Detail

Installed the latest version of the mod with Charging Gadgets in the same modpack and the game crash

### Log Attachment

[debug.log](https://github.com/user-attachments/files/16534496/debug.log)
[latest.log](https://github.com/user-attachments/files/16534497/latest.log)

### OPTIONAL: To Produce

1-Install Moonlight
2-Install JEI
3-Install Chargin Gadgets
4-Launch the game

### OPTIONAL: Which mods are affected?

charginggadgets-1.14-0
moonlight-1.21-2.14.5-neoforge
jei-1.21-neoforge-19.7.0.91

**Comment by MehVahdJukaar** [comment]
should be fixed

**Comment by Periam** [comment]
Fixed, mods installed and the game did not crash. Thanks
