### ISSUE TITLE
[🐞]: 0

### ISSUE THREAD

**Issue by zc1108aaa** [MehVahdJukaar/Moonlight#245]
### BEFORE CONTINUING:

- [X] Always check you are using the latest version of these mods and its dependencies
- [X] Remove known problematic rendering mods such as Optifine, Sodium and others

### Version-Loader

1.20.4-forge

### Moonlight Lib Version

0

### Issue Detail

0

### Log Attachment

[crash-2024-08-18_08.50.29-client.txt](https://github.com/user-attachments/files/16646887/crash-2024-08-18_08.50.29-client.txt)
0

### OPTIONAL: To Produce

0

### OPTIONAL: Which mods are affected?

0

**Comment by Xelbayria** [comment]
please don't use 0 on the required info: **Moonlight Lib Version** and **Issue Details**. It's not helping at all.

**Comment by MehVahdJukaar** [comment]
0

**Comment by MehVahdJukaar** [comment]
Every compat issue btw.doengade macaw trapdoors. Also don't expect more support as 1.20.4 is abandoned. I fact every compat isn't even for 1.20.4!!
