### ISSUE TITLE
[🐞]: Mixin Crash on During Load: Failed Injection Check

### ISSUE THREAD

**Issue by desagas** [MehVahdJukaar/Moonlight#252]
### BEFORE CONTINUING:

- [X] Always check you are using the latest version of these mods and its dependencies
- [X] Remove known problematic rendering mods such as Optifine, Sodium and others

### Version-Loader

1.21.1 neoforge - 21.1.49

### Moonlight Lib Version

moonlight-1.21-2.14.17-neoforge

### Issue Detail

Updating to 1.21.1 ..17 from .16 caused a mixin crash.

### Log Attachment

Log:
[latest.log](https://github.com/user-attachments/files/16947940/latest.log)

Debug:
[debug.log](https://github.com/user-attachments/files/16947941/debug.log)

Crash:
[crash-2024-09-10_10.23.20-client.txt](https://github.com/user-attachments/files/16947939/crash-2024-09-10_10.23.20-client.txt)

### OPTIONAL: To Produce

There are a lot of mods in my pack, this was caused by simply updating your mod. All other mods added and updated worked fine, until this one was updated.

I did not nor will I remove my rendering mods, as they were all working fine in .16 of your mod, but then the game stopped working in .17 of your mod.

### OPTIONAL: Which mods are affected?

Moonlight Lib, prevents game from fully loading.

**Comment by MehVahdJukaar** [comment]
got to love mixins and thier arcane errors that just happen in production

**Comment by desagas** [comment]
I am not sure if .18 fixed all of the errors, but, it fixed the game breaking ones. With .18, the game loads, and can be played.
