### ISSUE TITLE
[🐞]: Please update to 1.21.1

### ISSUE THREAD

**Issue by Shadowblitz16** [MehVahdJukaar/Moonlight#256]
### BEFORE CONTINUING:

- [X] Always check you are using the latest version of these mods and its dependencies
- [X] Remove known problematic rendering mods such as Optifine, Sodium and others

### Version-Loader

1.21-forge

### Moonlight Lib Version

na

### Issue Detail

na

### Log Attachment

na

### OPTIONAL: To Produce

na

### OPTIONAL: Which mods are affected?

na

**Comment by MehVahdJukaar** [comment]
the mod already has several files for 1.21.1!
