### ISSUE TITLE
[🐞]: join server but kicked with `Internal Exception` message

### ISSUE THREAD

**Issue by BredyAK** [MehVahdJukaar/Moonlight#258]
### BEFORE CONTINUING:

- [X] Always check you are using the latest version of these mods and its dependencies
- [X] Remove known problematic rendering mods such as Optifine, Sodium and others

### Version-Loader

1.20.1-forge

### Moonlight Lib Version

1.20-2.13.2

### Issue Detail

when i join the server, i'm kicked out with message:
> Internal Exception: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered

### Log Attachment

my minecraft client wasn't crashed, so there is no log.

### OPTIONAL: To Produce

1) install Moonlight to client and server
2) join the server
3) player is kicked out with the message above

**Comment by Xelbayria** [comment]
if there is no crash-report, you should add `latest.log`. Sometimes that can give Dev some clues for what's going on. 

& Do you have Every Compat installed?

**Comment by BredyAK** [comment]
> if there is no crash-report, you should add `latest.log`.

okay. here is my client log: [https://mclo.gs/PgbeYsm](https://mclo.gs/PgbeYsm).

> Do you have Every Compat installed?

~~yeap. i'm sure i've every compat installed.~~ Nope. I just know Every Compat is a mod name, i misunderstand this, i thought you ask me to make sure everything is compat with server. so, nope, i didn't install the mod Every Compat.

**Comment by MehVahdJukaar** [comment]
It is an every compat issue

**Comment by MehVahdJukaar** [comment]
closing as its not related to this

**Comment by BredyAK** [comment]
> > if there is no crash-report, you should add `latest.log`.
> 
> okay. here is my client log: https://mclo.gs/PgbeYsm.
> 
> > Do you have Every Compat installed?
> 
> ~yeap. i'm sure i've every compat installed.~ Nope. I just know Every Compat is a mod name, i misunderstand this, i thought you ask me to make sure everything is compat with server. so, nope, i didn't install the mod Every Compat.

@MehVahdJukaar i misunderstand this, please reopen the issue, sorry for causing your inconvenience.

**Comment by Xelbayria** [comment]
He's right, it's not related to moonlight. I took a look at the crash-report. Looks like a resource pack caused a lot of errors. You gotta make sure your CLIENT and the server are using the same version for every mods you have in the modpack.

**Comment by BredyAK** [comment]
> He's right, it's not related to moonlight. I took a look at the crash-report. Looks like a resource pack caused a lot of errors. You gotta make sure your CLIENT and the server are using the same version for every mods you have in the modpack.

yeah i'm sure about this.
