### ISSUE TITLE
[📦]: Unusual End - undetected logs

### ISSUE THREAD

**Issue by CaptConrad** [MehVahdJukaar/Moonlight#260]
### Before Continuing:

- [X] See [EC Backlog](https://github.com/users/MehVahdJukaar/projects/1/views/1) if someone already suggested a mod that you are going to suggest.

### Curseforge (Normal)

https://www.curseforge.com/minecraft/mc-mods/unusual-end

### FABRIC Version Availability

- [ ] 1.18.2
- [ ] 1.19.2
- [ ] 1.20.1

### FORGE Version Availability

- [X] 1.18.2
- [X] 1.19.2
- [X] 1.20.1

### MODID

unusualend

### Types

New wood type:
-Chorus Cane
![2024-10-10_21 56 05](https://github.com/user-attachments/assets/134a4b02-af31-4fe3-90c5-5b6dea5c13e4)

### Optional Details

The Chorus Cane planks are called chorus_nest_planks in the files.

**Comment by Xelbayria** [comment]
From what I see in the picture. there are 2 unique blocks using WoodTYpe "Chorus Cane"? 

does it have vanilla woodType: Oak, Birch, Spruce, so on...  even just one of Vanilla WoodType is good enough.


**EDIT:**
I just noticed "New WoodType", does that mean EveryCompat can't detect the woodType, Chorus Cane?

**Comment by CaptConrad** [comment]
EveryCompact doesn't detect Chorus Cane as a woodType but to be fair, the mod just got updated to 1.20.1 today.

**Comment by Xelbayria** [comment]
Gotcha. It's more of Enhancement for EveryCompat.  not module.

**Comment by Xelbayria** [comment]
oh forgot to mention this: 

EveryCompat detect the woodType by "bass" sound. Something to keep in mind. Does _Chorus Cane_ have "log". If yes, then you should let Dev know to update it's sound. BUT if it's a stem/cane, then it can be fixed (this is done in Moonlight lib)

**Comment by CaptConrad** [comment]
Yes it does have the "bass" sound.

The Block of Chorus Cane (block on the left in the picture) does have the "log" tag.

**Comment by CaptConrad** [comment]
Should also mention it's like bamboo where the "log" is a block of the stuff instead of it being an actual log from a tree if that makes any sense.

**Comment by Xelbayria** [comment]
### Fixed in v2.13.15

---


The texture part will be fixed in EveryCompat
