### ISSUE TITLE
[🗃]: Spectrum Noxwoods are not Supported as Woods - Undetected Logs

### ISSUE THREAD

**Issue by UnusedCactus** [MehVahdJukaar/Moonlight#264]
### Version

1.7.0

### Curseforge

https://www.curseforge.com/minecraft/mc-mods/spectrum

### Details

Spectrum 1.7.0 added 4 types of mushroom-based wood: Slate Noxwood, Ebony Noxwood, Ivory Noxwood, and Chestnut Noxwood. Log, wood (as in 6 bark-sided blocks), and "sapling" versions of these woods are listed as Noxcap Stems, Noxcap Hyphae, and Noxshrooms.

**Comment by Xelbayria** [comment]
Can you check if they have the sound "bass"? that's a common issue nowadays. There is nothing we can do to fix this on our side. Only devs can fix the woods' sound. 

EDIT: 
& can you update the mod to the latest version before you check?

**Comment by UnusedCactus** [comment]
I read the "version" thing as the earliest version the wood was added in,
not the version I'm actually playing, sorry. I am using the latest version
of Spectrum and the Compat. The thing that's missing isn't the sound, it's
that wood variations of blocks supported by the Compat don't include
Noxwoods. I assumed it was an unadded compatibility since the colored woods
added by Spectrum are supported.

**Comment by MehVahdJukaar** [comment]
we asked you to check if they have correct noteblock bass sound like all wood types should. if they dont thats the reason they arent detected and its their fault. so many modshave not been updated properly to 1.20 regarding this change

**Comment by UnusedCactus** [comment]
Putting a noteblock on a Noxwood block does make the noteblock produce a bass sound instead of any other sound. The behavior is consistent across the types of Noxwood.

**Comment by Xelbayria** [comment]
Ok, what is the ID of Noxwood?   

it should be similar to the format ID as Minecraft: `spectrum:noxwood_log`,

**Comment by UnusedCactus** [comment]
the logs are `spectrum:[slate/ebony/ivory/chestnut]_noxcap_stem` with the stripped variants listed as `spectrum:stripped_[slate/ebony/ivory/chestnut]_noxcap_stem`. The plank versions are listed as `spectrum:[slate/ebony/ivory/chestnut]_noxwood_planks` if you need those as well.

**Comment by Xelbayria** [comment]
i see. "stem" and `spectrum:ebony_noxcap_stem` for a log, 
`spectrum:ebony_noxwood_planks` for a plank

strange, I'll take a look.

**Comment by f-raZ0R** [comment]
Bumping this github issue, this is due to the discrepancy between the log being nox*cap*, and the plank being nox*wood*

**Comment by Xelbayria** [comment]
LOG: oak_noxcap
PLANKS: oak_noxwood_planks
STRIPPED_LOG: stripped_oak_noxcap_stem
WOOD: oak_noxcap_hypae

correct?

**Comment by f-raZ0R** [comment]
stripped log is stripped_TYPE_noxcap_stem, 2x2 bark block is TYPE_noxcap_hypae

**Comment by Xelbayria** [comment]
my previous post is updated and can u check to make sure all good

**Comment by f-raZ0R** [comment]
Log would be WOODTYPE_noxcap_stem, but other than that all good
also STRIPPED_WOOD, which would be stripped_WOODTYPE_noxcap_hyphae

**Comment by f-raZ0R** [comment]
there's also WOODTYPE_noxcap_block (the blocks that *arent* the log, that are on top of the mushroom), and WOODTYPE_noxcap_gills (a shroomlight equivalent, basically), although I don't think those would be relevant for your purposes

**Comment by Xelbayria** [comment]
They are relevant to what i need to know. thanks for the info.

**Comment by MehVahdJukaar** [comment]
is this still an issue?

**Comment by f-raZ0R** [comment]
https://github.com/MehVahdJukaar/Moonlight/blob/ac23af864148b295cda9909428606ef9123b5d44/common/src/main/java/net/mehvahdjukaar/moonlight/api/integration/CompatWoodTypes.java#L26

you seem to have only done it for... two of the four noxshroom woods? ivory and slate still don't have blocks added for them

**Comment by f-raZ0R** [comment]
> https://github.com/MehVahdJukaar/Moonlight/blob/ac23af864148b295cda9909428606ef9123b5d44/common/src/main/java/net/mehvahdjukaar/moonlight/api/integration/CompatWoodTypes.java#L26
> 
> you seem to have only done it for... two of the four noxshroom woods? ivory and slate still don't have blocks added for them

@Xelbayria ?

**Comment by Xelbayria** [comment]
I was busy & sorry about that. That's the correct file via `CompatWOodTypes.java` 
that's where undetected woodTypes are added.

**Comment by f-raZ0R** [comment]
Yeah, and you only actually... added it for two of the four wood types.
There's no WoodType.Finder.simple call for ivory or slate noxwood, and they don't get picked up by moonlight for stuff like IW or EveryCompat

**Comment by Xelbayria** [comment]
it was someone else who added these 2 woodTypes long time ago. I'll add it to Moonlight. please be patient.

**Comment by MehVahdJukaar** [comment]
Odd I thought I added all four. Weird

**Comment by Xelbayria** [comment]
**MehVahdJukaar**, You did in v2.13.14

@f-raZ0R, have you updated Moonlight Lib to v2.13.14. these woods you speak of should be included. 

EDIT:
took a look at the method, I see it has included the suffix via `_noxcap_stem` 

f-raZOR, is the suffix correct? 

& I'll be doing some quick test on Moonlight Lib with EveryCompat to see if everything is in order

**Comment by Xelbayria** [comment]
I ran a test and it's not working. Will be working on this.

**Comment by Xelbayria** [comment]
### Fixed in v2.13.15
