### ISSUE TITLE
[🐞]: Ars Nouveau too many archwood plank variants.

### ISSUE THREAD

**Issue by Dominus-Sicarum** [MehVahdJukaar/Moonlight#267]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1

### Loader

Forge

### EveryCompat Version

2.6.87

### Moonlight Lib Version

2.13.17

### Issue with mods

Ars Nouveau

### Issue Detail

Not sure if it belongs here, or in moonlight lib, but here we go:

After the recent patch that added Archwood Log detection, archwood plank related recipes multiplied. E.g. there's now 4 times as many (or 5 with Ars Elementum) Chipped plank varians, despite there being only one archwood plank and all of those differenly named items being exactly the same.

Same with Storage Drawers, Beautiful Campfires and so on. While not a gamebreaking issue, it clutters recipe viewers (JEI, EMI) immensely.

**Comment by MehVahdJukaar** [comment]
Yeah previously I only used to detect just blue one for this very reason. Whatever the recent update was it will be rolled back

**Comment by Xelbayria** [comment]
### ROLLED BACK in v2.13.18
