### ISSUE TITLE
[🐞]: Crash when playing 1.20.1 Essential mod and moonlight lib

### ISSUE THREAD

**Issue by dereck1020321323** [MehVahdJukaar/Moonlight#268]
### BEFORE CONTINUING:

- [X] Always check you are using the latest version of these mods and its dependencies
- [X] Remove known problematic rendering mods such as Optifine, Sodium and others

### Version-Loader

1.20.1-forge

### Moonlight Lib Version

moonlight-1.20-2.13.18-forge.jar

### Issue Detail

Missing required datapack registries: Moonlight: Soft_Fluids, moonlight:map_markers

This error appeared when trying to play the supplementaries mod, along side other mods and the Essential mod (mod that allows free multiplayer worlds)

Mods Used: 
Call of yucatan
Essential
Rubidium
Xaeros Minimap
Supplementaries
Geckolib
Citadel
breezy
Auroras
Alex Caves
![Captura de pantalla 2024-10-29 101825](https://github.com/user-attachments/assets/6ad919c2-5012-4c4a-b27a-82a1d15cc617)

### Log Attachment

Missing required datapack registries: Moonlight: Soft_Fluids, moonlight:map_markers

**Comment by Xelbayria** [comment]
Ensure **Version Loader** is correct. it was `1.21-forge` and the information is saying it's `1.20.1-forge`

if your minecraft crashed. you need to add Crash-report and latest.log

**Comment by MehVahdJukaar** [comment]
essentals problem. Dont use that mod anyways, it got ingame purchases and this bug is 100% their fault for fucking up mod added datapack registries

**Comment by MehVahdJukaar** [comment]
oh and btw there is no such thing as "payed multiplayer". You can play online any time, just open lan, get a vpn pogram and let your friend conect. alternatively run a local dedicated server on your machine. 
If you really need a mod to makeit easier use e4mc. 
using essentials is a rookie mistake
