### ISSUE TITLE
[🐞]: version "fabric_1.20-2.13.21" is missing on modrinth

### ISSUE THREAD

**Issue by MrRedstoneToGo** [MehVahdJukaar/Moonlight#270]
### BEFORE CONTINUING:

- [x] Always check you are using the latest version of these mods and its dependencies
- [X] Remove known problematic rendering mods such as Optifine, Sodium and others

### Version-Loader

1.20.1-fabric

### Moonlight Lib Version

fabric_1.20-2.13.20

### Issue Detail

Just add this file.
I'm reporting this because the latest 1.20 fabric version of supplementaries (1.20-3.0.4) requires "fabric_1.20-2.13.21" moonlight lib, which is obviously not there. I also looked on CurseForge and there was the correct version.

### Log Attachment

[2024-11-03-7.log](https://github.com/user-attachments/files/17611612/2024-11-03-7.log)

### OPTIONAL: Which mods are affected?

Supplementaries

**Comment by Xelbayria** [comment]
Added!

**Comment by MrRedstoneToGo** [comment]
Thanks
