### ISSUE TITLE
[🐞]: 2.13.43 breaks every single EveryCompat texture

### ISSUE THREAD

**Issue by xhatz** [MehVahdJukaar/Moonlight#287]
### BEFORE CONTINUING:

- [X] Always check you are using the latest version of these mods and its dependencies
- [X] Remove known problematic rendering mods such as Optifine, Sodium and others

### Version-Loader

1.20.1-FORGE

### Moonlight Lib Version

moonlight-1.20-2.13.43

### Describe the Issue

The latest version for 1.20.1 breaks all textures from every compat (wood good)

### Log Attachment

none

**Comment by Xelbayria** [comment]
Update Moonlight Lib to v2.13.44.

EDIT: 
closing this blc 2.13.43 is no longer the current version.
