### ISSUE TITLE
[Issue] Crash at startup

### ISSUE THREAD

**Issue by Nekkok** [MehVahdJukaar/Moonlight#29]
I'm having this issue which can't let me to initiate the game, it refers to something about ResourceKey[minecraft:enchantment / supplementaries:stasis]
[crash-2022-08-11_15.03.33-server.txt](https://github.com/MehVahdJukaar/Moonlight/files/9308939/crash-2022-08-11_15.03.33-server.txt)

**Comment by MehVahdJukaar** [comment]
This has to be an incompatibility with some other mod as it does not happen on its own. do you have any mod that do something with enchantments?

**Comment by Nekkok** [comment]
You were completely right. It was enchancement mod, which seems quite buggy atm. Sure I could close the issue, but now I'm having a new one. Sending you the new logs:
[latest.log](https://github.com/MehVahdJukaar/Moonlight/files/9331631/latest.log)
[crash-2022-08-13_16.48.16-client.txt](https://github.com/MehVahdJukaar/Moonlight/files/9331632/crash-2022-08-13_16.48.16-client.txt)

**Comment by MehVahdJukaar** [comment]
Seems like something with sodium accessing confgs too early. Try deleting it's config file. I don't see this mod mentioned here so its not related

**Comment by Nekkok** [comment]
Enchancement got updated and it solved the error with your mod, apparently. Unfortunately, it shows a new error :/
[latest.log](https://github.com/MehVahdJukaar/Moonlight/files/9334073/latest.log)

**Comment by MehVahdJukaar** [comment]
If you are not on 1.19.2 check you are using compatible versions as the latest ones both work for 1.19.2 only. I think it was supplementaries 0.13 and moonlight 0.15

**Comment by Nekkok** [comment]
Well, I'm on 1.19... supplementaries 0.13 and moonlight 0.15 in combination don't work. So I suppose we could close this issue, if you're not maintining this version anymore.

**Comment by MehVahdJukaar** [comment]
I need a crash report. Also be sure you are using supplementaries verison for 1.19

**Comment by Nekkok** [comment]
I swear my modpack went crazy... it's working! Sorry and thanks for your help. I know you're full focused on porting this mod and snowy spirit to fabric. As a reminder, I made the translation of advancement frames to es_es and now I'm making one to snowy spirit too, as a token of gratitude : )

**Comment by MehVahdJukaar** [comment]
Cool glad I could help! When thanks for the translations. I'll update the repo soon as right now it has the old forge only version
