### ISSUE TITLE
1.19x crash (launches but stuck on MC load screen) 

### ISSUE THREAD

**Issue by Z1p-x** [MehVahdJukaar/Moonlight#30]
[crash-2022-08-13_15.37.41-server.txt](https://github.com/MehVahdJukaar/Moonlight/files/9332377/crash-2022-08-13_15.37.41-server.txt)

I am using Fabulously Optimized mod pack and wanted to add Supplementaries/Moonlight. However at launch Minecraft is stuck at main menu loading screen and flickers back and forth without loading.  Currently on MC 1.19.2.

**Comment by MehVahdJukaar** [comment]
Does this still happen?

**Comment by XOX-CH** [comment]
Better Nether and Better End are not compatible in Moonlight Lib. 1.19.2

**Comment by MehVahdJukaar** [comment]
I cant replicate. Just made a new instance, added those 2 mods plus my mods and I can create and play in a new world just fine

**Comment by XOX-CH** [comment]
I re-tested them all and found MOD: Wilder Wild and they are out of tune after I removed MOD: Wilder Wild the Moonlight Lib works very well with a better nether better end I suspect MOD: Wilder Wild's pot
