### ISSUE TITLE
Crash with WilderWild and BetterX

### ISSUE THREAD

**Issue by SplendidAlakey** [MehVahdJukaar/Moonlight#31]
**MC** 1.19.2
**[QSL](https://modrinth.com/mod/qsl)** 4.0.0 beta 9
**[WilderWild](https://modrinth.com/mod/wilder-wild)** 1.0.5
**Moonlight Lib** 2.0.17 (it's not needed for any of the mods, only to reproduce the crash; I personally need it for Supplementaries which doesn't have to be installed to reproduce the crash)
**[BCLib](https://www.curseforge.com/minecraft/mc-mods/bclib)** 2.1.0
**[BetterEnd](https://www.curseforge.com/minecraft/mc-mods/betterend)** 2.1.0
**[BetterNether](https://www.curseforge.com/minecraft/mc-mods/betternether)** 7.1.0

To reproduce:

1. Install WilderWild, Moonlight and BCLib
2. Install either BetterEnd or BetterNether (or both, in which case BetterNether will be blamed for the crash)
3. Launch the game and crash

BetterX mods don't seem to be incompatible with WilderWild on their own, but only with Moonlight present.

Removing either WilderWild, Moonlight Lib or both BetterX mods lets the game start normally. Initially reported to WilderWild here: https://github.com/Soro335/WilderWild/issues/85. Since then every mod on the list has been updated, but the crash is still reproducible. I updated the logs to reflect that.

Logs include latest.log and crash log for the BetterEnd crash, but only the latest.log for BetterNether, because it does not generate a crash log: https://gist.github.com/Footage2-Amply-Pounce/e7506db63847f6f7f315af3cddee93c6

**Comment by MehVahdJukaar** [comment]
Whatever this is I'm pretty sure it's not on my end as it doesn't mention the mod in the logs and seems to be an issue with feature placement and this mod doesn't even touch worldgen

**Comment by Xfrtrex** [comment]
WilderWild Dev here, seems an issue with BetterX, As it crashes without Moonlight

**Comment by SplendidAlakey** [comment]
I personally couldn't reproduce it without MoonLight, but either way yeah it's 99% not a MoonLight issue.
