### ISSUE TITLE
Performance issues?

### ISSUE THREAD

**Issue by Muvkina** [MehVahdJukaar/Moonlight#32]
I'm not 100% sure if moonlight is to blame for the issue I am having but I have noticed that my game freezes when opening the creative menu and switching between tabs. I had no clue as to how to go about debugging this so I installed the spark mod for profiling. The only large abnormality I can find myself is something from moonlight in the tick step that is taking up 18% of the tick times(vs 25% total time): here is the spark log. Let me know if this is not an actual issue or if its not moonlights problem. https://spark.lucko.me/G4Xmy6l9Xt

**Comment by Muvkina** [comment]
Specifically it looks like its moonlight's api for getting fuel burn time.

**Comment by Muvkina** [comment]
I've basically confirmed this removing any mods that depend on moonlight lib and moonlight lib itself it both makes inventories open instantly and rei load instantly(was taking 1.6minutes before to load rei!) I tried testing without rei and such however nothing seemed to help till removing moonlight. Unfortunately one of my favorite mods relies on moonlight-lib(every compat) so I would love to see this maybe be fixed if possible. But unless another mod is causing moonlight lib to be slow it almost definitely looks as its an issue here.

**Comment by MehVahdJukaar** [comment]
Good find. I had a value swapped out and it would constantly try to register stuff to the burn time map. It's fixed now

**Comment by tubBandit** [comment]
I seem to be having the same issue with forge 1.19.2 causing REI to take forever to load.

**Comment by MehVahdJukaar** [comment]
That is not the same issue. Also I use Rei and it loads normally. Get a spark report or something

**Comment by tubBandit** [comment]
> That is not the same issue. Also I use Rei and it loads normally. Get a spark report or something

thank you for getting back to me. I will try and grab some more info and create a new issue.
