### ISSUE TITLE
To play in 1.19.1 it requires 1.19.2 Forge version

### ISSUE THREAD

**Issue by ZaptorI** [MehVahdJukaar/Moonlight#37]
Hi. The last update of the supplementary mod (2.1.2) requires the latest version of moonlight (2.0.26),  `Mod supplementaries requires moonlight 1.19.2-2.0.26 or above`, but it turns out that versions of moonlight after 2.0.17 require forge version 43.1.1 which makes no sense when playing on version 1.19.1. This makes it impossible to use moonlight 2.0.17 onwards in versions from 1.19.1

Here the crash reason: 
` Mod moonlight requires forge 43.1.1 or above
                Currently, forge is 42.0.9
        Mod Version: 1.19.2-2.0.26`

**Comment by MehVahdJukaar** [comment]
I'll remove the 1.19.1 mark then

**Comment by ZaptorI** [comment]
Sure, but this makes it impossible to play the newest versions of mods that requires, in fact, the newest versions of moonlight for 1.19.1. You can't add support for those versions in forge 42.0.9, which is required for 1.19.1?

**Comment by MehVahdJukaar** [comment]
No it just makes It impossible to play the newest version of the mod with 1.19.1. I don't really see any reason anybody would want to say on 1.19.1 instead of 1.19.2

**Comment by ZaptorI** [comment]
That's what I'm saying. Aanyone who wants to use the latest version of supplementaries for 1.19.1 simply can't. Tthe reasons are several, in my case, there're mods that haven't yet reached 1.19.2 so we cant update the modpacks to 1.19.2 version. 

So, instead of updating to 1.19.2, it's best to try and upgrade mods to newer versions of them, keeping the same version whenever indicated. The problem comes when the creator, you, isn't able to differentiate which version of forge he has set for his own mod, thus creating the incompatibility for which I have opened this issue, apparently in vain.

Since you don't intend to fix or update this problem, maybe you should, as you said in the first post, remove the 1.19.1 compatibility flag to avoid other misunderstandings with your mod instead of marking this as fixed, because it isn't.

**Comment by ZaptorI** [comment]
That's what I'm saying. Aanyone who wants to use the latest version of supplementaries for 1.19.1 simply can't. The reasons are several, in my case, there're mods that haven't yet reached 1.19.2 so we cant update the modpacks to 1.19.2 version.

So, instead of updating to 1.19.2, it's best to try and upgrade mods to newer versions of them, keeping the same version whenever indicated. The problem comes when the creator, you, isn't able to differentiate which version of forge he has set for his own mod, thus creating the incompatibility for which I have opened this issue, apparently in vain.

Since you don't intend to fix or update this problem, maybe you should, as you said in the first post, remove the 1.19.1 compatibility flag to avoid other misunderstandings with your mod instead of marking this as fixed, because it isn't.

**Comment by MehVahdJukaar** [comment]
Try the file I posted. I downgraded the verison checker too. Don't think they would have any problem working there as pretty much most mods work between .2 and .1 in both orders

**Comment by MehVahdJukaar** [comment]
Also if that's giving issues you can always use an old version of both mods. I don't plan to support older versions unfortunately
