### ISSUE TITLE
Connecting to server that uses Moonlight - crash

### ISSUE THREAD

**Issue by shkabo** [MehVahdJukaar/Moonlight#38]
I'm not sure if this is due to the server or due to this mod/lib, or due to some other 3rd party mod causing this, but when I tried to connect to the server that's using your mod/lib with the vanilla client, I've got this error. (using Better MC fabric 1.19.2 v5 server locally)
![2022-09-19_11 01 37](https://user-images.githubusercontent.com/1276333/191176216-b7818610-cb39-4f2e-bd3e-7f79cf286d70.png)

Any type of info will be helpful for debugging this issue and helping me determine what's the root cause of this.
Sorry in advance if it's not related to this mod/lib.

**Comment by MehVahdJukaar** [comment]
hm I can't replicate this with just a couple mod I have. it must be some mod messing up with my datapack registries. Fabric doesnt support them natively so some mixins in vanilla are required. I wonder if those are failing silently, possibly due to some other mod doing the same. Does the log say anything? (server & client since I'm not sure which side it is)

**Comment by MehVahdJukaar** [comment]
Ok so try going into your server world folder then data/ and delete fabricRegistry.dat. I was able to replicate this only with an old world that didnt have the mod. I'm trying to investigate how to do this properly

**Comment by shkabo** [comment]
here are the logs from the server https://mclo.gs/fH8jLaP, nothing that points out to this. If you want to replicate this, I can give you the steps to reproduce, but not sure if it's due to this or the modpack that I'm using

**Comment by MehVahdJukaar** [comment]
No it's not a problem with the mods you have its a problem with my mod and I need to figure out how to do it :/
What I know is that it works on a newly generated world on a server so it must be some file in the world folder (I thought it was that fabricRegistry but aparently that's only for maps)

**Comment by shkabo** [comment]
You can try it like this. 
- Download server from [here](https://www.curseforge.com/minecraft/modpacks/better-mc-fabric)
- Install it with the scripts provided in it
- Run the server and try to connect on it, you'll see the error

If you want, I can send you my discord user and we can talk to solve this, of course if it's actually this mod that's causing an issue, and not some relation with other mods

**Comment by MehVahdJukaar** [comment]
I'll give it a shot

**Comment by MehVahdJukaar** [comment]
So I did all that and I was able to connect. I still believe its something that does not happen on new worlds. Also to note I did try this with both supplementaries and moonlight latest version but that shouldnt have made a difference

**Comment by shkabo** [comment]
> So I did all that and I was able to connect. I still believe its something that does not happen on new worlds. Also to note I did try this with both supplementaries and moonlight latest version but that shouldnt have made a difference

That's odd. Then it looks like it might be something with my minecraft client. I'll try to re-install (w/o any mods) and try to connect. I'll let you know. Thanks once again for checking :)

**Comment by MehVahdJukaar** [comment]
So just to confirm this also happens if you run your server on a new world?

**Comment by shkabo** [comment]
I'm not using moonlight in my client, just on the server, and I'm getting that error when I try to connect on it. Am I doing something wrong or do I need moonlight in my client as well ?
Server is installed with the script from that modpack and new world is created that way.

**Comment by MehVahdJukaar** [comment]
you do need it on both. its not a server only mod. Infact I dont even know how your instance manages to launch as that modpack includes supplementaries and everycompat which both require it

**Comment by shkabo** [comment]
Thanks for your time invested to investigate this, but it looks that it's on my end.
Closing this one.
