### ISSUE TITLE
Insufficient maximum stack size

### ISSUE THREAD

**Issue by Asapin** [MehVahdJukaar/Moonlight#40]
I was playing Medieval Minecraft v6.5 modpack, and after 1.5-2 hours the server has crashed with org.objectweb.asm.tree.analysis.AnalyzerException, and the stacktrace mentions this mod, so I thought I'd report it just in case.

Here's the full stacktrace: https://pastebin.com/bXymx1tb

**Edit:** Increasing stack limit to 1.5Mb using "-Xss1536k" parameter seems to fix the issue

**Comment by MehVahdJukaar** [comment]
You run out of memory

**Comment by Asapin** [comment]
Seems like the issue was indeed with available ram. After updating the modpack and increasing memory limit the issue disappeared.
