### ISSUE TITLE
1.19.2 Crash using the Two Latest Versions

### ISSUE THREAD

**Issue by ModernGamingWorld** [MehVahdJukaar/Moonlight#43]
[crash-2022-10-14_09.56.38-client.txt](https://github.com/MehVahdJukaar/Moonlight/files/9787526/crash-2022-10-14_09.56.38-client.txt)

**Comment by MehVahdJukaar** [comment]
Did you update my other mods aswell?

**Comment by P3rf3ctXZer0** [comment]
Yes also my crash is serverside
My crash is server side 
https://gist.github.com/P3rf3ctXZer0/f2be16b26e91fe52a686f3fe1ef2af60
