### ISSUE TITLE
1.19.2 Serverside crash using latest version, had to revert to 0.34.

### ISSUE THREAD

**Issue by pokesmells** [MehVahdJukaar/Moonlight#45]
Using Fabric 0.14.19

**Comment by pokesmells** [comment]
travelers-backpack-1.19.2-8.2.3

everycomp-1.19.2-2.0.7

[Universal]CTOV-v3-1-2-overriding

mcw-roofs-2.2.1-mc1.19.2-fabric

supplementaries-1.19.2-2.2.6-fabric

These are all the mods I updated.

**Comment by Poke097** [comment]
I suspect it's either everycomp or CTOV. but most likely everycomp.

**Comment by Poke097** [comment]
Actually, just figured out I also updated this: 
supplementaries-1.19.2-2.2.6-fabric

I didn't get a crash-log so I was a bit confused

**Comment by Poke097** [comment]
I had to record the log live just to see what crashed it before start up lol

**Comment by pokesmells** [comment]
Whenever it crashed, it didn't give me a crash-log, I'll post a video of what happened.

https://user-images.githubusercontent.com/33227568/195941296-c4d0919b-5b8b-4aca-9f16-e999e7b696c5.mp4

**Comment by pokesmells** [comment]
I suspect it might be Supplimentaries, and Every compact.

**Comment by pokesmells** [comment]
The 0.36 version works completely fine on Client-side, I tested it 5 times by launching and going into a world, and closing rinsing and repeating, and it can also join the server with the 0.34 version and the server also has the updated version of all those mods btw

**Comment by MehVahdJukaar** [comment]
Is this happening on latest version?
