### ISSUE TITLE
Now crashing on client-side with new 0.37 version.

### ISSUE THREAD

**Issue by pokesmells** [MehVahdJukaar/Moonlight#46]
After updating to the 0.37 version, it breaks each time. 
[crash-2022-10-15_14.06.49-client.txt](https://github.com/MehVahdJukaar/Moonlight/files/9792904/crash-2022-10-15_14.06.49-client.txt)

**Comment by pokesmells** [comment]
I figured out why it crashed on the client-side, basically Curseforge is telling me to update from 0.36 and instead of giving me the 0.37 version it says it's incompatible and if you press the download button, it downloads the 0.34 version.

**Comment by MehVahdJukaar** [comment]
Wouldn't this be a problem with cueseforge? Why was this reopened?
