### ISSUE TITLE
Potential Bug

### ISSUE THREAD

**Issue by andrew0030** [MehVahdJukaar/Moonlight#47]
Hey!
I recently got a [bug report](https://github.com/andrew0030/SwampierSwamps/issues/9), from the looks of it my mixins fail. I wasnt able to gather much from the log, but from the looks of it _I think_ Moonlight API seems to be using a class that isnt available on all systems.
[error.txt](https://github.com/MehVahdJukaar/Moonlight/files/9796344/error.txt)
I may be wrong, but Im hoping this error means something to you!

**Comment by MehVahdJukaar** [comment]
I have no idea. First that class it mentions is included in a library used by the game, second I'm not even using it. Maybe it's something with quilt

**Comment by andrew0030** [comment]
This issue has been resolved on my end!
