### ISSUE TITLE
1.19.2 ``moonlight-1.19.2-2.0.38`` causing null point exception when joining a single player world and ``moonlight-1.19.2-2.0.39-40`` causing startup hang and world load issues.

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [MehVahdJukaar/Moonlight#48]
Forge Version: 43.1.43
Moonlight: moonlight-1.19.2-2.0.38
Modpack: https://www.curseforge.com/minecraft/modpacks/fiction-friction/files/4033444 or https://www.technicpack.net/modpack/fiction-friction-8gb.1942926

https://gist.github.com/P3rf3ctXZer0/1237c32b2a8ee00650eed883f80e17f8

Or if you want a simple answer
- Update moonlight-1.19.2-2.0.37 to moonlight-1.19.2-2.0.38
- Go to singleplayer
- when validating pack it gets interrupted with texture something 256 = null. (In the future I will take a solid screenshot.)

Notes
I love your mod and your coding when good is solid but your QA not so much. Next time you want to make a version just @me and send me a dropbox or whatever you have with a note and I will test it and makes sure it works. You like releasing updates before any testing and honestly it's a nightmare. Reach me here. Zer0Necrosis#2995 I know being a modpack dev that curse is not always fast either and I have 43 projects I have helped QA so I am legit able to figure things out. However I cannot code. I will do my best to help maintain this awesome mod.

**Comment by P3rf3ctXZer0** [comment]
I know you released a new update I will test it when I solve a different problem I am experiencing.

**Comment by P3rf3ctXZer0** [comment]
Completely fixed thank you.

**Comment by P3rf3ctXZer0** [comment]
This is not fixed now it just hangs at startup.

**Comment by P3rf3ctXZer0** [comment]
(I am tired for validity sake I will close this til I make sure.

**Comment by P3rf3ctXZer0** [comment]
Sorry misclicked anyways the issue is correct

![A2pmodE 1](https://user-images.githubusercontent.com/10351221/196618662-a38e09c8-849a-4a6d-834d-938438ed02bd.png)

moonlight-1.19.2-2.0.39
everycomp-1.19.2-2.0.8

**Comment by MehVahdJukaar** [comment]
Is this still an issue? I can't see anything in that log you posted, can you upload the new latest.log and debug.log?

**Comment by P3rf3ctXZer0** [comment]
Give me 5 mins or discord me.

**Comment by MehVahdJukaar** [comment]
If it freezes debug.log should still contain info. Feel free to send on my discord bugs channel

**Comment by P3rf3ctXZer0** [comment]
Random question - is start up greatly increased?

**Comment by MehVahdJukaar** [comment]
If you add mods startup will slowly increase as more blocks and items have to be registered and setup task be run

**Comment by P3rf3ctXZer0** [comment]
![jDYgLoP 1](https://user-images.githubusercontent.com/10351221/196619396-b5c653f0-708b-41da-a084-919875ea14e8.png)

https://gist.github.com/P3rf3ctXZer0/da95a380aca834067769a7d00788f498 

This debug folder appeared but its empty

**Comment by MehVahdJukaar** [comment]
It's in the log folder

**Comment by P3rf3ctXZer0** [comment]
https://gist.github.com/P3rf3ctXZer0/da95a380aca834067769a7d00788f498
<- Contains debug and latest .logs

**Comment by MehVahdJukaar** [comment]
Did it crash there or was it stil loading? Seems like it was interrupted while loading stuff and didn't crash on itself. I don't see anything wrong there, last line is a logged by silent gear

**Comment by MehVahdJukaar** [comment]
Can you confirm that you gave MC enough ram and that if is freezing indefinitely even when left on its own for a few min?

**Comment by P3rf3ctXZer0** [comment]
It has take over 20 mins
... 

https://github.com/MehVahdJukaar/Moonlight/issues/48#issuecomment-1283526189

**Comment by MehVahdJukaar** [comment]
But you have enough ram?

**Comment by P3rf3ctXZer0** [comment]
I should unless you change the requirements. These load fine.
![vI2ZhSh 1](https://user-images.githubusercontent.com/10351221/196620664-98b1ab0e-4850-4a57-9178-06ae4acd5314.png)

![E3m3Coy 1](https://user-images.githubusercontent.com/10351221/196620762-8b0129db-9b4f-47fd-8bd0-9b2ad1be1ee3.png)

![evNnHV2 1](https://user-images.githubusercontent.com/10351221/196620846-c952715a-3038-4973-9882-a7b82ebe3876.png)

![dftpvTX 1](https://user-images.githubusercontent.com/10351221/196620914-ed25c116-63ff-4024-84eb-5eaef3d4719b.png)

![7PdflBj 1](https://user-images.githubusercontent.com/10351221/196621029-a370ddf8-680b-4bac-a4c7-52971b774b72.png)

**Comment by MehVahdJukaar** [comment]
I know that if you se the amount of ram too low the game will still try to load but the java VM will waste huge amount of time trying to constantly garbage collect stuff to keep the ram low slowing stuff down. Try to increase it a bit more and see if it presists

**Comment by P3rf3ctXZer0** [comment]
So is it a one time startup? this pack was made with weaker pcs in mind.

**Comment by MehVahdJukaar** [comment]
Idk what mod you are using moonlight with but if it's every compat, that mod requires a lot of ram as it simply adds many blocks especially if you have many wood or furniture mods

**Comment by P3rf3ctXZer0** [comment]
Setting it to 17120MB

**Comment by MehVahdJukaar** [comment]
If this is an actual issue it's a hard one to track down so first I want to be sure it's not just low on ram

**Comment by MehVahdJukaar** [comment]
Also you can check the ram used in taks manager

**Comment by P3rf3ctXZer0** [comment]
Great we managed to proc my passive ``Finds rare and obscure yet detrimental bugs.`` Henceforth why I have worked with people and projects before.

Also whoops forget to get the latest ones before testing just now since youd didn't DM me on discord I figured you were afk or unable to work on things XD

![BMqkET3 1](https://user-images.githubusercontent.com/10351221/196623158-495760ac-e32f-4848-a5de-3e1c8713ac24.png)

**Comment by P3rf3ctXZer0** [comment]
So yeah it is doing nothing. Nevermind it is pissing off bitdefender ... is trigger antivirus a new feature XD

The same time the game was unresponsive bitdefender was scanning hard.

**Comment by P3rf3ctXZer0** [comment]
![Sc05mG6 1](https://user-images.githubusercontent.com/10351221/196624403-66230bf2-6d4f-43ab-9742-acf90e046497.png)
It booted.

**Comment by P3rf3ctXZer0** [comment]
Debug files generated
![hZOVLvi 1](https://user-images.githubusercontent.com/10351221/196624608-d252beb1-fff8-4998-9ba2-82440987cd15.png)

**Comment by P3rf3ctXZer0** [comment]
loading a single player world
![vhR6pBk 1](https://user-images.githubusercontent.com/10351221/196625728-b3f64e9b-a0a2-4be8-b06c-d1bf05562b2d.png)

**Comment by MehVahdJukaar** [comment]
Can you just send the latest.log? That's a crash now so it has stuff I can look at. Also what about the load time? For discord idk what your user is. You can see mine by joining the supplementaries discord

**Comment by MehVahdJukaar** [comment]
The other issue was likely low ram + antivirus scanning as you said

**Comment by P3rf3ctXZer0** [comment]
... you just proved you are only glancing at messages ... 

In the very first post I put my discord user tag Zer0Necrosis#2995

**Comment by P3rf3ctXZer0** [comment]
Its now 3am and I am getting exhausted

**Comment by Gamemassa** [comment]
Hi, I'm not sure if my crash is related to this thread, but it sounds like it might be, so here's my latest.log

https://gist.github.com/Gamemassa/fb7ee98e9b1d12f03b0948203a6a48e3

**Comment by P3rf3ctXZer0** [comment]
40 loads but crashes / hangs on world load. https://github.com/MehVahdJukaar/Moonlight/issues/48#issuecomment-1283559330

Also breaks world even after removed.

**Comment by Gamemassa** [comment]
> 40 loads but crashes / hangs on world load. [#48 (comment)](https://github.com/MehVahdJukaar/Moonlight/issues/48#issuecomment-1283559330)
> 
> Also breaks world even after removed.

Not to sound sarcastic, but logically the fact that it breaks your world after you removed it isn't surprising because the game is probably trying to load assets that are no longer there.

**Comment by Gamemassa** [comment]
> Can you just send the latest.log? That's a crash now so it has stuff I can look at. Also what about the load time? For discord idk what your user is. You can see mine by joining the supplementaries discord

Hi, did you happen to look at my latest.log file that I linked earlier today, and if so, is it related to this thread or do I need to move it? Also, do you prefer us to send log files as .txt attachments or GitHub Gist links? I can reattach if necessary.

**Comment by MehVahdJukaar** [comment]
> ... you just proved you are only glancing at messages ...
> 
> In the very first post I put my discord user tag Zer0Necrosis#2995

Indeed, it replied while I was following a lecture

**Comment by MehVahdJukaar** [comment]
> Hi, I'm not sure if my crash is related to this thread, but it sounds like it might be, so here's my latest.log
> 
> https://gist.github.com/Gamemassa/fb7ee98e9b1d12f03b0948203a6a48e3

This has nothing to do with this mod. That crash is caused by a mixin from terraform dirt failing to apply, possibly conflicting with another

**Comment by MehVahdJukaar** [comment]
> 40 loads but crashes / hangs on world load. [#48 (comment)](https://github.com/MehVahdJukaar/Moonlight/issues/48#issuecomment-1283559330)
> 
> Also breaks world even after removed.

I still need the full report as an exception message doesn't mean anything

**Comment by P3rf3ctXZer0** [comment]
When I fix issues my pack not related to your mod I will worry about testing

**Comment by P3rf3ctXZer0** [comment]
Okay finally your mod is not broken. It was a complex series of issues I am closing this.

**Comment by Gamemassa** [comment]
> > Hi, I'm not sure if my crash is related to this thread, but it sounds like it might be, so here's my latest.log
> > https://gist.github.com/Gamemassa/fb7ee98e9b1d12f03b0948203a6a48e3
> 
> This has nothing to do with this mod. That crash is caused by a mixin from terraform dirt failing to apply, possibly conflicting with another

Oh! Ok, thank you so much for confirming. I will redirect my crash report to the Terraform team and see what they say.

Also, best of luck with your lectures!

**Comment by MehVahdJukaar** [comment]
Thanks :D

> > > Hi, I'm not sure if my crash is related to this thread, but it sounds like it might be, so here's my latest.log
> > > https://gist.github.com/Gamemassa/fb7ee98e9b1d12f03b0948203a6a48e3
> > 
> > 
> > This has nothing to do with this mod. That crash is caused by a mixin from terraform dirt failing to apply, possibly conflicting with another
> 
> Oh! Ok, thank you so much for confirming. I will redirect my crash report to the Terraform team and see what they say.
> 
> Also, best of luck with your lectures!
