### ISSUE TITLE
1.19.2 Debug file causing export failure / Debug folder causing lag in explorer.

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [MehVahdJukaar/Moonlight#49]
![eOAOQms 1](https://user-images.githubusercontent.com/10351221/196849154-821fdc05-86fd-486c-804b-86c27ab72994.png)

**Comment by P3rf3ctXZer0** [comment]
possible solution force it into a moonlightresourcepack.zip afterwords?

**Comment by MehVahdJukaar** [comment]
What's that? Of you mean the resource dump debug folder that should always stay empty. If you leave that option on it will significantly slow boot times. It's only useful to check out the generated textures once

**Comment by P3rf3ctXZer0** [comment]
Huh it is always full after I start the game. ... you said its supposed to be empty but it is always full ...

**Comment by P3rf3ctXZer0** [comment]
default exported options for everycompat

``
[general]
	#Puts all the added items into a new Every Compat tab instead of their own mod tabs. Be warned that if disabled it could cause some issue with some mods that have custom tabs
	creative_tab = true
	#Allows the mod to try to remap and convert other blocks and items from other compat mods that have been uninstalled from one world. This was made so one can uninstall such mods seamlessly having their blocks converted into Evety Compat counterparts
	remap_other_mods = false
	#Clears out and remaps all blocks registered by this mod belonging to uninstalled wood types to air or oak wood
	remap_self = true
	#Makes dynamic assets that are generated depend on loaded resource packs. Turn off to make them just use vanilla assets
	assets_depend_on_loaded_packs = true
	#Creates a debug folder inside your instance directory where all the dynamically generated resources will be saved
	debug_resources = true
``

**Comment by MehVahdJukaar** [comment]
Last option should be false. I'll double check to see that's not it's default

**Comment by Xelbayria** [comment]
is this issue related to Every Compat?

**Comment by P3rf3ctXZer0** [comment]
Closing due to stale.
