### ISSUE TITLE
[1.19.2] Crash on startup

### ISSUE THREAD

**Issue by NielsPilgaard** [MehVahdJukaar/Moonlight#51]
Happens with `moonlight-1.19.2-2.1.1.jar` and `moonlight-1.19.2-2.0.40.jar`, probably other versions too 😄 

https://gist.github.com/NielsPilgaard/02cfa2a93255c4baf0b9609b7d18be9b#file-gistfile1-txt-L16

**Comment by MehVahdJukaar** [comment]
I've never seen something like that. It's a mixin issue of a mixin I had since quite some time ago. It must be an incompatibility. Can you also check you don't have duplicate mods in your folder?

**Comment by NielsPilgaard** [comment]
No duplicate mods in my mods folder :)

**Comment by MehVahdJukaar** [comment]
Can you try on a clean install? I can't tell which mod it's conflicting with

**Comment by NielsPilgaard** [comment]
It does not happen in an instance with only Moonlight 🤔

**Comment by MehVahdJukaar** [comment]
Then something is definitely wrong as thousand of people have used the mod in this update and none has reported this. Maybe forge is outdated? Are you using a launcher?

**Comment by NielsPilgaard** [comment]
It must be a mod conflict, I just don't see which other mod could cause a an issue with the Moonlight mixin :P

Tests were made using `1.19.2-43.1.47` and the CurseForge App.

**Comment by MehVahdJukaar** [comment]
Hmm weird I'll have a look. Got some time so I'll do some testing. If this is an issue I'll get angry at my discord since nobody reported nothing XD

**Comment by MehVahdJukaar** [comment]
Ok so I did some testing by downloading enigmatica 9 and updating all mods and forge and it does boot for me so I have no clue :/

**Comment by NielsPilgaard** [comment]
What o_O something in my instance must be messed up then. Thanks for the help!

**Comment by MehVahdJukaar** [comment]
If you do figure it out let me know

**Comment by NielsPilgaard** [comment]
Removing Every Compat, Supplementaries and Moonlight fixed the issue oddly enough. Re-adding them made the issue reappear.

Could this be the issue?

```
[21:23:04] [main/WARN] [mixin/]: Reference map 'everycomp-common-refmap.json' for everycomp-common.mixins.json could not be read. If this is a development environment you can ignore this message
21:23:04.686
[21:23:04] [main/WARN] [mixin/]: Reference map 'everycomp.refmap.json' for everycomp.mixins.json could not be read. If this is a development environment you can ignore this message
```

I see no `everycomp.refmap.json` in the everycomp jar

**Comment by MehVahdJukaar** [comment]
That's a warn and is harness I believe. I got yesterday somebody else that had that same issue and it's so weird. I'll likely make that mixin optional. So weird that I can't replicate with your exact same mods

**Comment by MehVahdJukaar** [comment]
I made that mixin optional. Fortunately only thing that it did was fixing a vanilla bug
Still i've asked and that error loads when a class loads before mixins are ready which is something that I didnt even know was possible and must be caused by something extremely cursed as that's never supposed to happen for any class. Maybe launcher?

**Comment by NielsPilgaard** [comment]
I'm using the CurseForge App. Race condition perhaps?

**Comment by NielsPilgaard** [comment]
> I made that mixin optional.

Same old crash with the new version sadly :( thanks anywho

**Comment by NielsPilgaard** [comment]
I've done a complete reinstall of Minecraft + Forge, same issue :/ I must have cursed hardware.

**Comment by MehVahdJukaar** [comment]
Ok so I've got some more info on this. I've got some other people try that setup and they couldn't replicate. I also now know that the only possible way this can happen is if some mod can load a class before mixins are ready to be applied. This should never happen and if it does it's an issue with said mod. The way this can work is in a mixin plugin as those load before mixins are applied and well before mod loading. I myself don't have any of those mixins plugin but you can tell other mods that do as there's an extra line in their mixins.json

**Comment by MehVahdJukaar** [comment]
I have an idea how to fgiure this out. If you message me on discord one of these days I can send you a mod that will crash immediately as that creative tab class is loaded so we see who exactly loaded it

**Comment by MehVahdJukaar** [comment]
Actually I realized I can't even do that as to do so I would have to use a mixin and we all know how that will go... You could try to see which mod uses a mixin plugin in their jsons, tho that still doesn't explain why it worked for me and other people. Also there's a bit more on this on the forge discord non api modding channel

**Comment by NielsPilgaard** [comment]
I finally tracked it down, it was the mod `ME Requester`. Thanks for all your help!

**Comment by MehVahdJukaar** [comment]
Good catch! Talked to the author and we fixed it
