### ISSUE TITLE
[1.19.2] Crash on startup with latest version

### ISSUE THREAD

**Issue by ribbonleaves** [MehVahdJukaar/Moonlight#52]
Hi! The crash is definitely Moonlight Lib, as without it and its dependents it runs to the title screen. Not a duplicate jar either, so I don't know what is happening.

[(https://gist.github.com/ribbonleaves/27107daed43da6a30d97deaf0cfebc98)](https://gist.github.com/ribbonleaves/27107daed43da6a30d97deaf0cfebc98)

**Comment by MehVahdJukaar** [comment]
You are using 1.18 version on 1.19

**Comment by MehVahdJukaar** [comment]
Of label mod (the mod bundles in part of this, that they package name is like that)

**Comment by ribbonleaves** [comment]
oh my god thank you so much! I'm embarrassed XD just checked and on Curseforge it says the 1.18.2 version is labelled for 1.19.2, so the app i guess assumed it was for that...that's CurseForge being CurseForge lol
