### ISSUE TITLE
CME Race condition when launching the game

### ISSUE THREAD

**Issue by pupnewfster** [MehVahdJukaar/Moonlight#54]
I am reporting this here as I am fairly certain it is on Moonlight's end and not JAOPCA. But recently after installing both Harvest Season and Immersive Weathering (I already had Supplementaries installed), I started getting sporadic CME's when launching Minecraft (sometimes it launches and other times it fails).

Crash Report: https://gist.github.com/pupnewfster/b618a23b041f2c352c275067a6855be2

It seems to reference [this](https://github.com/TheLMiffy1111/JAOPCA/blob/f73d91c2658b36345fb1dad527d816d3ba2c8f03/src/main/java/thelm/jaopca/data/DataCollector.java#L89) line in JAOPCA that just creates a new instance of vanilla's `MultiPackResourceManager`, and I suspect the issue is that given JAOPCA does this during mod construction (which is parallel on forge) it is possible that your mixin is iterating its list of listeners at the same time that other mods using this lib are being constructed and added to your internal list of listeners.

Versions:
Forge: 43.1.47
JAOPCA: 4.2.1.2
Moonlight: 2.1.4
Supplemetaries: 2.2.13
Harvest Season: 1.0.3
Immersive Weathering: 1.1.4

**Comment by pupnewfster** [comment]
I am *guessing* this is fixed now, given after testing launching 5 or so times  using:
Forge: 43.1.52
JAOPCA: 4.2.2.3 (which I had reproduced the crash with before updating anything else)
Moonlight: 2.1.6 (which includes https://github.com/MehVahdJukaar/Moonlight/commit/b631cc6eac40ed055a8cafda902d86b24fc562b5 which seems related)
Supplementaries: 2.2.16
Harvest Season: 1.1.1
immersive weathering: 1.2.2

I have not ran into it again. No idea if it is just due to updating various mods (including ones not listed above) the CME just happens to be extremely rare as timings of things shifted or if https://github.com/MehVahdJukaar/Moonlight/commit/b631cc6eac40ed055a8cafda902d86b24fc562b5 or commits in individual addons fixed it. Leaving this open for now in case you believe it is just chance that it I am no longer experiencing it, but if you did make changes that you believe fixed this feel free to close it. (I will comment if I end up running into it again)

**Comment by MehVahdJukaar** [comment]
Yeah I believed to have fixed it. Was something with a shared config map during mod setup which on forge runs in parallel
