### ISSUE TITLE
The new version of moonlight is crashing my server

### ISSUE THREAD

**Issue by 444wa** [MehVahdJukaar/Moonlight#59]
Hey, the title is exactly how it sounds, I know it is a pretty minor issue, but basically moonlight version 2.1.11 is preventing the server from starting up/always crashing on startup. I figure this because whenever the server Mod folder has version 2.1.10 or older, it will be able to start up just fine, no problem. Everyone who plays on my server has Moonlight Lib version 2.1.11, but they cannot interact with most of the Supplementaries Mod, as the server can only be up when it is on version 2.1.10.
 I have the console output from when this happened, maybe yall could take a look at this? Is it a really obvious solution that I am missing? I am not too good at this kind of stuff. Thank you in advance.

"
26.11 20:51:46 [Server] INFO java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'moonlight'!
26.11 20:51:46 [Server] INFO at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.14.10.jar:?]
26.11 20:51:46 [Server] INFO at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.10.jar:?]
26.11 20:51:46 [Server] INFO at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.14.10.jar:?]
26.11 20:51:46 [Server] INFO at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.10.jar:?]
26.11 20:51:46 [Server] INFO at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.14.10.jar:?]
26.11 20:51:46 [Server] INFO at net.minecraft.server.Main.main(Main.java:101) [server-intermediary.jar:?]
26.11 20:51:46 [Server] INFO at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.10.jar:?]
26.11 20:51:46 [Server] INFO at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.10.jar:?]
26.11 20:51:46 [Server] INFO at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.10.jar:?]
26.11 20:51:46 [Server] INFO at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.10.jar:?]
26.11 20:51:46 [Server] INFO Suppressed: java.lang.NoClassDefFoundError: net/minecraft/class_746
26.11 20:51:46 [Server] INFO at net.mehvahdjukaar.moonlight.api.platform.fabric.RegHelperImpl.lambda$register$3(RegHelperImpl.java:84) ~[moonlight-1.19.2-2.1.11-fabric.jar:?]
26.11 20:51:46 [Server] INFO at java.util.HashMap.computeIfAbsent(HashMap.java:1220) ~[?:?]
26.11 20:51:46 [Multicraft] Server shut down (starting)
26.11 20:51:46 [Multicraft] Restarting crashed server in 600.0 seconds
26.11 20:51:46 [Multicraft] Server stopped
"

**Comment by taucxti** [comment]
Same happening to me. I was able to fix it by removing Every Compat.

**Comment by MehVahdJukaar** [comment]
Crash report?

**Comment by taucxti** [comment]
Sorry, looking closer at the crash report I don't think it's the same issue as OP. I made a different thread here. https://github.com/MehVahdJukaar/Moonlight/issues/60
