### ISSUE TITLE
Latest Moonlight Library crashing game.

### ISSUE THREAD

**Issue by Cr4fTJuNkiE** [MehVahdJukaar/Moonlight#62]
[moonlight_crash-2022-12-01_12.37.20-server.txt](https://github.com/MehVahdJukaar/Moonlight/files/10134889/moonlight_crash-2022-12-01_12.37.20-server.txt)

Not sure what's going on here.

**Comment by MehVahdJukaar** [comment]
Downgrade macaw windows or wait for an every compat update

**Comment by MehVahdJukaar** [comment]
Also closing as I have many other duplicate issues of this

**Comment by Cr4fTJuNkiE** [comment]
Aaah, okay. This was fixed on the Forge version rather quickly. Thought it was fixed for Fabric too.

**Comment by MehVahdJukaar** [comment]
I tried but importing the new fabric version in the project lead to an unexplainable decompilation bug. I asked the authors and they didn't know either. I'll try again soon but if it still doesn't work I'll have no choice but to remove the module

**Comment by Cr4fTJuNkiE** [comment]
That sucks. Hopefully you'll get it sorted. Best of luck. : )
