### ISSUE TITLE
Client crash Incompatabily with Nyf's spider's 2.0, 1.19.2

### ISSUE THREAD

**Issue by netcore10** [MehVahdJukaar/Moonlight#63]
Nyf's spider's issues lead to an invalid discord link, my only option was to send one here.
[Mclo.gs/7JJELGb](https://mclo.gs/7JJELGb)

[crash-2022-12-03_18.34.31-client.txt](https://github.com/MehVahdJukaar/Moonlight/files/10147289/crash-2022-12-03_18.34.31-client.txt)

Can you shed some light on the problem?

**Comment by MehVahdJukaar** [comment]
I'm pretty sure it has nothing to do with this. It's a mixin error from 2 other mods and it points here just because I load those classes first

**Comment by netcore10** [comment]
Dangit, guess i need to investigate.

**Comment by MehVahdJukaar** [comment]
it say  #apugli:apugli.mixins.json:ExplosionMixin from mod apugli

**Comment by netcore10** [comment]
Thanks! All's fixed.
