### ISSUE TITLE
creashing when people try to log in to the server 1.19.2 fabric

### ISSUE THREAD

**Issue by papillo12** [MehVahdJukaar/Moonlight#67]
[crash-2022-12-12_03.35.37-server.txt](https://github.com/MehVahdJukaar/Moonlight/files/10204469/crash-2022-12-12_03.35.37-server.txt)
[crash-2022-12-12_03.45.02-server.txt](https://github.com/MehVahdJukaar/Moonlight/files/10204470/crash-2022-12-12_03.45.02-server.txt)
[crash-2022-12-12_03.47.44-server.txt](https://github.com/MehVahdJukaar/Moonlight/files/10204471/crash-2022-12-12_03.47.44-server.txt)

**Comment by MehVahdJukaar** [comment]
Issue coming from this mod. ishland.vmp
I don't see mine mentioned anywhere there

**Comment by papillo12** [comment]
Sorry the first crash report was for vmp, the other 2 are moonlight because I had already deleted vmp.

**Comment by MehVahdJukaar** [comment]
I can't tell. The log just mentions Minecraft classes. Not even a mixin or mod reference there so I have no idea

**Comment by papillo12** [comment]
Well, the only reason I realized it was your mod, is because I only updated 2 mods deeperdarker and moonlight, when I moved your mod to the previous version, the server stopped crashing when people tried to log in, in the client the game does not crash in the latest version.

**Comment by papillo12** [comment]
the bug has been fixed, I updated to the version you released today and I had no more problems, the problems I had with moonlight-1.19.2-2.1.16
