### ISSUE TITLE
Crash at startup (Fabric, mc 1.19.2)

### ISSUE THREAD

**Issue by ccrowles** [MehVahdJukaar/Moonlight#69]
As per title, I'm getting a startup crash and Moonlight seems to be the culprit (or possibly the interaction between Moonlight and some other mod but I can't pinpoint which one).

Logfile: [here](https://mclo.gs/KfqiMhm)

**Comment by MehVahdJukaar** [comment]
should be fixed

**Comment by ccrowles** [comment]
Can confirm, that fixed it. Thanks!
