### ISSUE TITLE
Mixing crash with Optifine

### ISSUE THREAD

**Issue by webmilio** [MehVahdJukaar/Moonlight#75]
The bug happens on minecraft `1.19.2`.

I'm running forge `43.2.3` along with Optifine `HD U I1 pre4` and Moonlight `2.1.22`. I've tried running it the latest Moonlight version `2.1.24` and the bug still happens. I'm not sure if Optifine is responsible or if Moonlight is.

[This issue is related to this one on the Optifine Github.](https://github.com/sp614x/optifine/issues/7203)
https://gist.github.com/webmilio/26bdbc33c40bef3f496acf90746e5aca

If the Gist is too short, I can reproduce the crash and upload the full log.

**Comment by MehVahdJukaar** [comment]
That's a create mixin

**Comment by webmilio** [comment]
Wait you're right...
