### ISSUE TITLE
Crash on start up.

### ISSUE THREAD

**Issue by OpheliaSakura** [MehVahdJukaar/Moonlight#76]
The game crashed whilst initializing game
Error: java.lang.NoSuchMethodError: 'void net.mehvahdjukaar.moonlight.api.resources.pack.DynamicTexturePack.addSimilarJsonResource(net.mehvahdjukaar.moonlight.api.resources.StaticResource, java.lang.String, java.lang.String)'

**Comment by MehVahdJukaar** [comment]
I need a log. Check all my mods are up to date

**Comment by OpheliaSakura** [comment]
Sorry, IW was out of date
