### ISSUE TITLE
Player crashed when he picked up a treasure map.

### ISSUE THREAD

**Issue by Giordy492** [MehVahdJukaar/Moonlight#79]
A player playing on my server crashed after putting a map from a chest to his inventory, with this error: "Internal exception:io.netty.handler.codec.DecoderException: java.io.IOException: packet 0/38 (ClientBoundMapItemDataPacket) was larger than I expected, found 1 bytes extra whilst reading packet 38"
After a backup I also tried to take some maps but I'm not having the same problem, what could it be?

if it's relevant I'm also using supplementaries, required by the IDAS mod

Here is his log, but there is no crash report.
[latest.log](https://github.com/MehVahdJukaar/Moonlight/files/10512688/latest.log)

**Comment by MehVahdJukaar** [comment]
says that his client doesnt have moonlight. i dont even know how he managed to log in
