### ISSUE TITLE
[Fabric] Moonlight lib crashes while generating world on SMP at fluid mixin transformation

### ISSUE THREAD

**Issue by fuzzyweapon** [MehVahdJukaar/Moonlight#81]
This happened while generating the world for the first time on SMP.  There are a lot of mods in this modpack so I'm going to try and generate a cleaner/more isolated repro, but just wanted to get this in.  This is not occurring with the same seed in client single player.

running moonlight 1.19.2-2.2.0 with Minecraft 1.19.2 + Fabric Loader 0.14.12

& `level-seed=8201860340638529` in `server.properties`

```
[20:16:13] [Server thread/WARN]: Error loading class: net/fabricmc/fabric/api/client/render/fluid/v1/FluidRenderHandlerRegistry (java.lang.RuntimeException: Cannot load class net.fabricmc.fabric.api.client.render.fluid.v1.FluidRenderHandlerRegistry in environment type SERVER)
[20:16:13] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.RuntimeException: Mixin transformation of net.mehvahdjukaar.moonlight.api.fluids.ModFlowingFluid failed
```
in
https://hastebin.com/ilisexuluf.yaml

**Comment by MehVahdJukaar** [comment]
Update the mod

**Comment by fuzzyweapon** [comment]
welp, that certainly helped.  >__>  Closing as not a bug

**Comment by MehVahdJukaar** [comment]
Yeah was fixed on latest version

**Comment by Sunconure11** [comment]
@MehVahdJukaar Is this still present? Because I ran into it on 1.19.2 still.

https://pastebin.com/GM6Pwwez

**Comment by Sunconure11** [comment]
I am on Quilt, of note.

**Comment by MehVahdJukaar** [comment]
It says that a mod called quilt status effect has a mixin which failed to be injected, possibli confincring with another mod. Should have nothing to do with this

**Comment by Sunconure11** [comment]
The milk issue is gone, but I am seeing something similar to this fluid issue.

https://github.com/MehVahdJukaar/Moonlight/issues/89
