### ISSUE TITLE
Latest update [moonlight-1.19.2-2.2.11-fabric] crashes game on launch

### ISSUE THREAD

**Issue by Caketaco** [MehVahdJukaar/Moonlight#84]
[Client Log](https://mclo.gs/o3DUUdk)

[Crash Log](https://mclo.gs/e38J5Bj)

Ruh roh!

**Comment by MehVahdJukaar** [comment]
Update supplementaries and snowyspirit. Unrelated

**Comment by Caketaco** [comment]
Whoops, updated supplementaries but forgot about snowyspirit, user error moment.

**Comment by Caketaco** [comment]
Nevermind, both updated and issue persists.

![image](https://user-images.githubusercontent.com/39420594/221344049-dd75296d-86df-4012-b6b3-bc1934b60f8e.png)

[Client Log](https://mclo.gs/r9giwXU)

[Crash Log](https://mclo.gs/tLP84Ts)

**Comment by Caketaco** [comment]
Launching the game with only Indium, Fabric Api, Sodium, Supplementaries, Snowy Spirit, and Moonlight Lib. Game crashes.
[Client Log](https://mclo.gs/w7SdOUf#L325)
[Crash Log](https://mclo.gs/E77TqF7)

Removing Snowy Spirit appears to fix this.

All mods are fully up to date.

Will make a new issue in Snowy Spirit's git

**Comment by MehVahdJukaar** [comment]
Hm i messed up. Downgrade supplementaries while i update snowy spirit.

**Comment by Caketaco** [comment]
Fixed
