### ISSUE TITLE
Minecraft doesnt start after installing lastest update.

### ISSUE THREAD

**Issue by KostromDan** [MehVahdJukaar/Moonlight#85]
Exit code 1.
No crash log.
log: [latest.log](https://github.com/MehVahdJukaar/Moonlight/files/10904335/latest.log)

**Comment by MehVahdJukaar** [comment]
uploaded a new version

**Comment by KostromDan** [comment]
[latest.log](https://github.com/MehVahdJukaar/Moonlight/files/10908583/latest.log)
nope

**Comment by MehVahdJukaar** [comment]
what in the actual frick

**Comment by KostromDan** [comment]
> what in the actual frick
Sorry if my English is bad, but I couldn't understand your answer even using translator.
If you meant that im using not lasted version, i used this, that uploaded 51 minutes ago at the moment of writing this comment.
![image](https://user-images.githubusercontent.com/90044015/223417246-ce365ab0-b4a0-4585-a396-ed76ebd10e71.png)

**Comment by MehVahdJukaar** [comment]
So I did test that third version I uploaded and it did work for me outside of Dev this time

**Comment by KostromDan** [comment]
> So I did test that third version I uploaded and it did work for me outside of Dev this time
yes, it fixed. Thanks.
