### ISSUE TITLE
Possible issue relating to... milk?

### ISSUE THREAD

**Issue by Sunconure11** [MehVahdJukaar/Moonlight#87]
https://pastebin.com/GM6Pwwez

My guess is that it is related to a mod that adds milk as a form of liquid.

**Comment by Sunconure11** [comment]
Doing some investigating on the error...

Create, Pehkui, Porting Lib, and Lithium all seem to use the same mixins that is being blamed. 

This is also happening on Quilt, of note.

**Comment by Sunconure11** [comment]
Looks like I reported this before, and forgot.

https://github.com/LunarLuned/Peculia/issues/4

**Comment by MehVahdJukaar** [comment]
This doesn't seem to be related to this mod

**Comment by Sunconure11** [comment]
Milk issue was fixed, but other mods seem to be having fluid issues with your mixins, so anything else to deal with fluids should go to this issue:

https://github.com/MehVahdJukaar/Moonlight/issues/89
