### ISSUE TITLE
Problem with recent update

### ISSUE THREAD

**Issue by ZebraTheZebra** [MehVahdJukaar/Moonlight#88]
Sorry this post is so short, typing about 5 minutes before i go to work and i had to make this account. I think the recent update made it so that stone blocks didnt have a tool type attributed to them. pickaxes took forever to mine stone and I isolated it to this mod by uninstalling everything else. Thanks

**Comment by idchlife** [comment]
@ZebraTheZebra same here.

**Comment by MehVahdJukaar** [comment]
I uploaded abuggy version that lasted for 5h before I took it down. Be sure you aren't on that one
