### ISSUE TITLE
Fluid mixin errors with multiple mods

### ISSUE THREAD

**Issue by Sunconure11** [MehVahdJukaar/Moonlight#89]
[latest.log](https://github.com/MehVahdJukaar/Moonlight/files/11042406/latest.log)
[crash-2023-03-22_12.23.29.1767-quilt_loader.txt](https://github.com/MehVahdJukaar/Moonlight/files/11042407/crash-2023-03-22_12.23.29.1767-quilt_loader.txt)
[crash-2023-03-22_12.26.27.9399-quilt_loader.txt](https://github.com/MehVahdJukaar/Moonlight/files/11042408/crash-2023-03-22_12.26.27.9399-quilt_loader.txt)

I'm noticing this with several mods. As these are likely all connected, I am consolidating them into one issue.

**Comment by Sunconure11** [comment]
Of note is that I am on Quilt, so that might have something to do with it.

**Comment by MehVahdJukaar** [comment]
so fun that having a class that loads early with mixins makes all unrelated issues possible show up here as my class name shows up on the stack trace. yes its the class taht laoded those failed classes slightly before they might have had but they would have simply failed later anyways. This seems to be a mixin problem from malum mod that is conflicting with some other unspecified mods. maye gobber

**Comment by Sunconure11** [comment]
Issue is deeper, and unrelated. Closing.
