### ISSUE TITLE
Error at instruction 114 - return value is null - Fabric 1.19.2 - Only in Console not in latest.log

### ISSUE THREAD

**Issue by xR4YM0ND** [MehVahdJukaar/Moonlight#90]
So i checked my console and there are some lines:
Line 448 - 497

[latest console log](https://gist.github.com/SpigotDE/bcfaedc36ba8ed5aaab11697be834cd7)

**Comment by MehVahdJukaar** [comment]
issue is unrelated. my class shows un in the stack trace just because it happened to be the first that loaded that failed vanilla class which had a failed mixin from some other mod
