### ISSUE TITLE
Mislabled Version For Latest Update

### ISSUE THREAD

**Issue by Sonifluous** [MehVahdJukaar/Moonlight#92]
I went to update my mods this morning and noticed that the Moonlight Lib mod had an update. When I did so, my game crashed, an upon further inspection found that the update is a 1.19.4 version update rather than a 1.19.2 version update that the mod is supposed to be. I figured the update was mixed up somehow, and simply rolled back the update to the previous version. Just wanted to leave a heads up in case anyone else runs into this issue!

**Comment by YOYOK9** [comment]
The forge version [moonlight-1.19.4-2.3.2-forge.jar] of the mod also has the fabric api marked as a required dependency.

**Comment by P3rf3ctXZer0** [comment]
Seems like MehVahdJukaar did that fix before bed with the number of errors. As someone who often grinds fixes ... it has all the tell tale signs.

**Comment by P3rf3ctXZer0** [comment]
![ivZeCwH 1](https://user-images.githubusercontent.com/10351221/227811923-3617cdf4-551c-4024-8153-89f8dcb62f0e.png)

**Comment by MehVahdJukaar** [comment]
fixed
