### ISSUE TITLE
Mining sack with shears crashed game

### ISSUE THREAD

**Issue by thelegitdolt** [MehVahdJukaar/Moonlight#93]
https://gist.github.com/thelegitdolt/64d3e9d59df72f608073b5e1fc53e32b < crash report
https://gist.github.com/thelegitdolt/ca0fd514d65f739496073b5aa76e7422 < latest.log

**Comment by MehVahdJukaar** [comment]
are you sute you are using the latest version?

**Comment by thelegitdolt** [comment]
> supplementaries-1.19.2-2.2.63.jar                 |Supplementaries               |supplementaries   
 supp version
> moonlight-1.19.2-2.2.21-forge.jar                 |Moonlight Library             |moonlight   
Moonlight version

**Comment by thelegitdolt** [comment]
no :(

**Comment by thelegitdolt** [comment]
i shall update and see if it fixes it. i'm sorry for wasting time sir mehvahdjukaar
