### ISSUE TITLE
[Crash 1.19.2]Crash on Entering Config

### ISSUE THREAD

**Issue by SaltSouls** [MehVahdJukaar/Moonlight#94]
## Description
When entering the config screen for any mods that use Moonlight it causes the game to crash. This was tested on both supplementaries and haunted harvest.

## Version
- MC: 1.19.2
- Forge: 43.2.8
- Moonlight: 2.2.27

## Logs
[Latest](https://gist.github.com/SaltSouls/2c450d68ee584381084e9afa0794e7f1) | [Crash](https://gist.github.com/SaltSouls/ee598567d21a08b88085b88444ee7d08) | [Debug](https://gist.github.com/SaltSouls/feef9b9ea8ffa26f32a52f63b9688923)

**Comment by MehVahdJukaar** [comment]
should be fixed now
