### ISSUE TITLE
Consider open-source license

### ISSUE THREAD

**Issue by poly2it** [MehVahdJukaar/Moonlight#96]
An open-source license for this library can only do good for the community. It would let users make use of what has been implemented here, to develop the Minecraft modding ecosystem. An open-source license would let people contribute to your project to assist in development.

**Comment by MehVahdJukaar** [comment]
True. I'm to be fair only reason I had are was because I was too lazy to look up and choose another as art is default one on cf

**Comment by MehVahdJukaar** [comment]
done

**Comment by poly2it** [comment]
Thank you so much! Now I'll be able to integrate this library in my mod-pack as well.
