### ISSUE TITLE
[1.19.2] Intermittent crash on server startup while using JAOPCA

### ISSUE THREAD

**Issue by DelviousCrafts** [MehVahdJukaar/Moonlight#98]
An intermittent crash occurs during the server startup event when Moonlight Lib is used in conjunction with JAOPCA. This does not occur every time the server loads, but consistently enough to be a nuisance. Reported originally [here](https://github.com/TheLMiffy1111/JAOPCA/issues/275) to JAOPCA as it was the mod listed in the crash as the issue. Requested that a report be made to Moonlight Lib. 

Versions:
- Minecraft: 1.19.2
- Forge: 43.2.8
- Moonlight Lib: 2.2.28 - forge
- JAOPCA: 4.2.7.13

Crash Report:
[crash-2023-04-06_12.49.19-fml.txt](https://github.com/MehVahdJukaar/Moonlight/files/11175488/crash-2023-04-06_12.49.19-fml.txt)

**Comment by MehVahdJukaar** [comment]
was this fixed for you?

**Comment by Delvious** [comment]
This has not been fixed with updating to latest version of moonlight lib. Currently using version 2.2.29 and still getting intermittent crashes that look identical to the one I submitted with the initial report. I can upload a new log/crash report if needed a little later today.

**Comment by DelviousCrafts** [comment]
[Latest Log](https://gist.github.com/DelviousCrafts/1c8a516c36b3b59a067cd7565cc4f05b)
[Crash Report](https://gist.github.com/DelviousCrafts/b16421a341f36b9cb91849cf94859553)
[Debug Log](https://gist.github.com/DelviousCrafts/d7432d179fb475b6df4a8e533d9ce09b)

Hopefully something in these helps. This is the most recent instance. It does seem to happen somewhat less often now, but is still an ongoing issue.

**Comment by aaronhowser1** [comment]
https://gist.github.com/aaronhowser1/57e2ca1e580c588bf1c1cddb88dad918 I also got this

**Comment by DelviousCrafts** [comment]
updating to version 2.2.31 seems to (tentatively speaking) resolved this issue. I have loaded the server several times with no crash as of yet. This would, generally speaking, happen every about third time I loaded up the server. I will make sure to let you know if I do get another crash.

**Comment by Xelbayria** [comment]
You can re-open this issue if it comes back. Be sure to include the current version that caused the crash.
