### ISSUE TITLE
Startup crash involving this mod

### ISSUE THREAD

**Issue by Fortun4tus** [MehVahdJukaar/Moonlight#99]
[latest.log](https://github.com/MehVahdJukaar/Moonlight/files/11186038/latest.log)

[crash-2023-04-09_18.41.34-client.txt](https://github.com/MehVahdJukaar/Moonlight/files/11186039/crash-2023-04-09_18.41.34-client.txt)

I updated supplementaries, immersive weathering and this mod and ended up with this issue, can you at least point me to the right direction.

**Comment by MehVahdJukaar** [comment]
Idk why this would ever happen as it seems impossible. I'm aware of this issue I just can't test it on my ide as I dont have a quilt environment not I plan to. Fabric alone is enough no way Ill start some triple loader setup. Anyways I'll just say that quilt is not supported

**Comment by Fortun4tus** [comment]
Please don't brush it away saying that quilt is not supported, by the way it worked before moonlight version 2.2.26 and before supplementaries 2.2.63, but can you please figure out a way to fix this, or maybe if you really can't just get someone who can. Thank you.

**Comment by Fortun4tus** [comment]
Turns out it is a supplementaries squared issue.
